### ISSUE TITLE
Feature Request: Suggestion for work item references in commit messages

### ISSUE THREAD

**Issue by Glober777** [microsoft/azure-repos-vscode#159]
Dear Team,

I really like your extension and use it extensively on a daily basis. Thank you so much!

I wonder if it's possible to add a feature that would list out corresponding work items as I try referencing them in the commit messages (like it's done in VSTS web interface)?

Thanks!

**Comment by jeffyoung** [comment]
Hi @Glober777.  Thanks for using the extension and providing your feedback!

In an upcoming release we'll be adding a 'Team Associate Work Items' command that will query your work items (either the ones assigned to you or the ones returned from any pinned query you have in your VS Code user settings), allow you to choose one via the QuickPick menu and then we'll add it to your commit message.  We need a new API from VS Code before we can release it (they're working on that now) so hopefully we'll be able to release this soon.

Would that be what you're looking for?

**Comment by Glober777** [comment]
Hi @jeffyoung, it seems close. Would there be an ability to have that command triggered by typing '#' character within the commit message box? 

Ideally, it would be really great if the QuickPick list would show up right within the commit message box and not within the command prompt, but as far as I understand VSCode may not yet support that.

**Comment by jeffyoung** [comment]
At this point, it doesn't appear to be possible.  The SCM APIs provide an ability to attach a command to run when CTRL+ENTER is pressed within that input box, but not hook on any particular key.  (Admittedly, what you described would be ideal... much like (or exactly like) what happens here in GH.)

**Comment by papadi** [comment]
Can you please explain how this feature works exactly? I don't see anything happening. I tried invoking it before/after doing the commit, before/after typing something as commit message... I see no difference. Only my messages goes into the commit. No item is associated.

**Comment by kaylangan** [comment]
@papadi please see #314

**Comment by seckin92** [comment]
For what it's worth, I assigned the `#` key as a custom shortcut for the Associate Work Items command, this is the closest I got to the desired behavior, I think it's good enough until the SCM APIs expose a keypress hook! 😇 

```json
    {
        "key": "oem_7",
        "command": "team.AssociateWorkItems"
    }
```

**Comment by dfaroi** [comment]
@kaylangan same for TFVC see #433

**Comment by domjg85** [comment]
I would also love to hear any progress or workaround on this? We're using tfs API and workitems are not being associated to check-ins, very frustrating
