### ISSUE TITLE
create PR using configured TFS credentials

### ISSUE THREAD

**Issue by carlin-q-scott** [microsoft/azure-repos-vscode#161]
I use a different user account for TFS than my normal user account. This is problematic with Chrome because it will always submit my current user account credentials which are wrong and therefore I have to very frequently re-auth with TFS the website. Visual Studio 2015 opens Chrome as my TFS user, bypassing this issue flawlessly. I would like this same feature ported to this VS Code extension.

**Comment by jpricketMSFT** [comment]
Thanks for your feedback and your suggestion!
