### ISSUE TITLE
TFVC: Error TF30063 when attempting to connect to a "Server" workspace

### ISSUE THREAD

**Issue by eogas** [microsoft/azure-repos-vscode#176]
It's not particularly clear from the documentation whether or not this is intentional, but it seems that there is currently only support for local TFVC workspaces.  When attempting to connect to a "Server" workspace, I get the following debug output:

    2017-04-13T19:29:26.584Z - info:   [11492] *** FOLDER: c:\devtools ***
    2017-04-13T19:29:26.595Z - debug:  [11492] Looking for an External Context at c:\devtools
    2017-04-13T19:29:26.596Z - debug:  [11492] No External Context at c:\devtools
    2017-04-13T19:29:26.603Z - debug:  [11492] Looking for TFVC repository at c:\devtools
    2017-04-13T19:29:26.604Z - debug:  [11492] TFVC Creating Tfvc object with localPath='undefined'
    2017-04-13T19:29:26.605Z - debug:  [11492] Using TFS proxy: undefined
    2017-04-13T19:29:26.606Z - debug:  [11492] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\tf.exe'
    2017-04-13T19:29:26.610Z - debug:  [11492] TFVC Repository created with repositoryRootFolder='c:\devtools'
    2017-04-13T19:29:26.612Z - debug:  [11492] TFVC Repository.CheckVersion
    2017-04-13T19:29:26.616Z - debug:  [11492] TFVC: tf add -noprompt -?
    2017-04-13T19:29:26.628Z - debug:  [11492] TFVC: spawned new process (duration: 9ms)
    2017-04-13T19:29:26.645Z - debug:  [11492] TFVC: spawned new process (duration: 15ms)
    2017-04-13T19:29:27.184Z - debug:  [11492] TFVC: add exit code: 0 (duration: 566ms)
    2017-04-13T19:29:27.192Z - debug:  [11492] TFVC Repository.FindWorkspace with localPath='c:\devtools'
    2017-04-13T19:29:27.194Z - debug:  [11492] TFVC: tf workfold -noprompt ********
    2017-04-13T19:29:27.203Z - debug:  [11492] TFVC: spawned new process (duration: 8ms)
    2017-04-13T19:29:28.172Z - debug:  [11492] TFVC: workfold exit code: 100 (duration: 978ms)
    2017-04-13T19:29:28.176Z - debug:  [11492] TFVC errors: TF30063: You are not authorized to access mycooltfsserver\MyTeamProjectCollection.

Running `team signin` after receiving this failure results in the following error:

`(team) No Team Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder that contains a repository.`

Sorry for the bad report if this is intentionally not supported at this time, but it wasn't clear from the readme.

**Comment by jeffyoung** [comment]
Hi @eogas.   Yes, I'll take an item to make it more apparent in the README that the workspace needs to be local.  We've got an item on the backlog to support Server workspaces at some point, but I don't have an ETA on that.

**Comment by ddavisringtown** [comment]
+1 supporting server workspaces (where can we upvote -- Connect?).

**Comment by eogas** [comment]
@jeffyoung cool, thanks for the info!

**Comment by jeffyoung** [comment]
Hi @ddavisringtown.  This is a good a place as any to upvote 👍  (I prefer keeping everything related to this project within the GitHub, at least as much as possible).

**Comment by sudhin** [comment]
+1 supporting server workspaces

**Comment by AlexisColes** [comment]
+1 for supporting server workspaces

**Comment by Nehmiabm** [comment]
+1 for supporting server workspaces

**Comment by codypersinger** [comment]
+1 for supporting server workspaces please

**Comment by yoyurec** [comment]
+1

**Comment by jincopunk** [comment]
Also requesting

**Comment by cosmanovich** [comment]
+1

**Comment by gmarica01** [comment]
+1

**Comment by markusmauch** [comment]
+1 for server workspace support

**Comment by Eria-Hajk** [comment]
^2

**Comment by alejandro5042** [comment]
+1

**Comment by schwarzie2478** [comment]
+1

**Comment by szilvaa** [comment]
+1

**Comment by hardcoreparkour** [comment]
+1 went through all that setup to find out that it was not going to work. back to team explorer (standalone I go)

**Comment by eogas** [comment]
**Please stop leaving +1's on this thread.** Github added the thumbs up/down for a reason. Turns out that reason was that it's obnoxious to get an e-mail every few days with nothing but "+1" in it.

**Comment by benshabatnoam** [comment]
+1

**Comment by voyager18** [comment]
+1

**Comment by mattdkerr** [comment]
Can you exclude Git-TFS folders, though? It detects the remote workspace, despite not being a proper TFS workspace that you'd want to use like that.

**Comment by seonjung-jeon** [comment]
+1

**Comment by osterworks** [comment]
+1

**Comment by limitgreen** [comment]
+1

**Comment by PleaseStopAsking** [comment]
+1

**Comment by makafsal** [comment]
+1

**Comment by MidRoh** [comment]
+1

**Comment by kschwarz1980** [comment]
+1

**Comment by CarlosSanches07** [comment]
+1

**Comment by svendebaets** [comment]
+1 for server workspaces

**Comment by rneurink** [comment]
+1

**Comment by nevzathayri** [comment]
+1

**Comment by jkim506** [comment]
@jeffyoung Any updates on this?

**Comment by pierodamafalda** [comment]
+1 for server workspaces

**Comment by carloreggiani** [comment]
Still no way to connect to TFS 2017?

**Comment by chrisbchicken** [comment]
@jeffyoung Any updates on server workspace support?

**Comment by amintabar** [comment]
Hi everybody,
So how can I connect to my local TFS server?!

**Comment by WalterEbbers** [comment]
@jeffyoung Are there updates on when to expect server workspace support?

**Comment by kaylangan** [comment]
We do not currently have any plans to support server workspaces.

**Comment by marcdill** [comment]
Since @kaylangan says there are no plans to support server workspaces, are there available work arounds that we can use without having to open our Visual Studio IDE's that we can use?

**Comment by cwuethrich** [comment]
@marcdill you can still use local workspaces. This extension works fine with local workspaces.
https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/decide-between-using-local-server-workspace?view=tfs-2018

**Comment by JarredMiles** [comment]
I'm not sure about anyone else, but at my workplace we have a very large solution with over 100k files, so local workspaces are not on option for us. It would be nice if this plugin did support them so that we don't have to rely on Visual studio for all our tfvc needs. Or at the very least someone at Microsoft can create a standalone tool for tfvc. I prefer to work with a lighter editor since Visual Studio can be very slow and bulky.

**Comment by cwuethrich** [comment]
@JarredMiles we do have more than 100k files as well. You don't have to sync the whole workspace.

**Comment by josersleal** [comment]
> @marcdill you can still use local workspaces. This extension works fine with local workspaces.
> https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/decide-between-using-local-server-workspace?view=tfs-2018

Sorry to bring bad, horrible news but it does not: https://github.com/microsoft/azure-repos-vscode/issues/465

Basically the plugin is unusable for those with this issue

**Comment by bbouzan** [comment]
Still no way to connect to server workspaces?

**Comment by qJake** [comment]
2 years later and still no Server Workspace support? 😢

**Comment by MRGaraffa** [comment]
I recently started using VS Code.  While setting up Azure Repos, I ran into an issue where the 'Teams (!)' notification stated that I was linking to a Server workspace, which was not supported.
After failing on several attempts to get this working, I finally found a solution:
   1. Open up a VS command prompt;
   2. Type 'tf workspaces /collection:<name of your collection>';
   3. Enter your Microsoft account name and password linked to the Server workspace;
   4. Restart VS Code
   5. Click on the 'Team (!)'
   6. Enter your Private Account Token and hit enter
My workspace is still set to Server and I am able to see changes, check out files (required separate extension), exclude, and undo.
I hope this helps others resolve this problem!

**Comment by NickCook-StruMIS** [comment]
+1 for server workspaces

**Comment by picolino** [comment]
Hello from 2020, any server workspaces will be released in this year, hm?

**Comment by qJake** [comment]
We just ended up migrating from TFVC to Git (DevOps) which VS Code has full support for.

Not a "solution" by any means, but TFVC is slowly losing popularity to Git, and I don't see this enhancement ever being completed if it's been 3 years already.
