### ISSUE TITLE
Wrong encoding when check in a changeset

### ISSUE THREAD

**Issue by scaillerie** [microsoft/azure-repos-vscode#188]
When I check in some changeset, the message is not saved correctly.

When entering "Ajout d'un bouton de création des articles", I got the following result in the history :
![image](https://cloud.githubusercontent.com/assets/2785888/25423905/9da101b4-2a66-11e7-9583-a0c327e6d63d.png)

If I save it through Visual Studio, there is no problem...

**Comment by jeffyoung** [comment]
Thanks @scaillerie.  I'll need to debug this at some point to figure what's going wrong.  Thanks for letting me know that it works fine with Visual Studio.

**Comment by mdschweda** [comment]
Also, line endings should be Windows style.

**Comment by reinaldoarrosi** [comment]
Any update on this?
I'm using VSCode 1.19.3 and vsts-vscode 1.122.0 and the issue still exists.
