### ISSUE TITLE
Connectivity Issue (to Team Services Online)

### ISSUE THREAD

**Issue by Glober777** [microsoft/azure-repos-vscode#240]
Dear Team,

I really like your extension and use it all the time, but with some resent changes in our corporate firewall it no longer works and here's the only error message that seems relevant:
![image](https://cloud.githubusercontent.com/assets/18121861/26338999/5bdb2584-3f8d-11e7-97a3-9c00a5ce3bab.png)

From what I understand it is having issues to connect to some URL(s) (most likely it gets an unexpected reply), and I need something that I could go to our IT Security folks with and ask them to punch a proper hole for the VSTS extension to work properly again. Is there a list of URLs that are used by the extension? Or is there a log file being kept somewhere that holds the communication history?

Interestingly enough, I can use the VSTS through the web browser without any issues. I'm sure that the problem is with the corporate firewall, as the extension can connect just fine if I try it outside our network.

Thanks,
Glober777

**Comment by jeffyoung** [comment]
Hi @Glober777.

To talk to Team Services, the extension uses the vsts-node-api npm package to do the communication (including the authentication).  The extension takes credentials and passes it along to that package to do all of the hard work.  Unfortunately, it doesn't seem to have any logging we could turn on to see what communication is being performed.  I think the best someone could do is use Fiddler to get a trace of the traffic.

I don't know what all of the settings would need to be set (or exactly how) to get this to work through the proxy, but I did find [some documentation](https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#how-do-i-configure-the-agent-to-bypass-a-web-proxy-and-connect-to-team-services) on how to set up the Team Services build agent to work with a proxy.  It might be worth a shot to start there.  If you do set it up, I'd definitely be interested in knowing the results.

And thanks for reporting the issue!
