### ISSUE TITLE
how to connect VS Code execution and TFS result ?

### ISSUE THREAD

**Issue by krogold** [microsoft/azure-repos-vscode#258]
Hello, 
I'm trying to connect VS Code and TFS in order to get TFS reporting for execution of Postman collections via VS Code. I configured VS Code appropriately (I think, I refered to this link:https://github.com/Microsoft/vsts-vscode) but I can't figure out how to get the results in the chosen build.
I work with TFS 2015 and the latest version of VS Code.
Has anyone done this ?

**Comment by jeffyoung** [comment]
Hi @krogold.  I need a bit more information about what you're trying to do.  This extension allows you to connect to TFS or Team Services by way of cloned Git repositories or TFVC workspaces.  It allows you to monitor builds, pull requests and work items.

If you're asking about how you can make REST calls against the TFS/Team Services APIs, there's overview documentation [here](https://www.visualstudio.com/en-us/docs/integrate/api/overview).  For build-specific calls, see [this page](https://www.visualstudio.com/en-us/docs/integrate/api/build/builds).  This extension _does_ make use of an npm package, [vso-node-api](https://www.npmjs.com/package/vso-node-api), that provides an object model used to make the REST calls.  There are a lot of examples of in this repository.
