### ISSUE TITLE
Extension creates latency, crashes VS Code

### ISSUE THREAD

**Issue by largeDachshund** [microsoft/azure-repos-vscode#261]
I just installed this extension.  I've tried to look through issues to see if this problem has already surfaced.  Couldn't find anything.

Here's a pic of the dev tools at crash: 
![image](https://user-images.githubusercontent.com/7054672/27403148-3c956f92-567e-11e7-9d47-1d515115c940.png)

here's the team extension dev log.  nothing to see here, except ridiculous latency on the fetch to VSTS. 
![image](https://user-images.githubusercontent.com/7054672/27403235-931b98be-567e-11e7-95ae-53ebff43a159.png)

I like the concept that VS Code should integrate with VSTS.  I must be missing something.  Or is this a bug?

**Comment by jeffyoung** [comment]
Hi @largeDachshund.  Thanks for trying out the extension!

Would you be able to provide the rest of the log file you've collected?  I'd like to see what other information is there.  The log file will tell me which TF client you're using, what version, etc.  Once I know that, we can see if we can track down why `tf status` is taking 6 - 7 seconds (for one, trying the same command at the command prompt).  I'd also be interested in understanding how many files you may have in your TFVC workspace (that's information I won't get from the logs).
