### ISSUE TITLE
How to setup a way to display the branch of changes?

### ISSUE THREAD

**Issue by ivanklevin** [microsoft/azure-repos-vscode#272]
How to setup a way to display the branch of changes: excluded changes and included changes. Need to display a tree change with folders and subfolders, as in visual studio. How to ignore folder node modules or other elements? 

<img width="451" alt="1" src="https://user-images.githubusercontent.com/19389565/27765191-0ae3bff6-5eb4-11e7-90cb-afbcc4edd2d9.png">
<img width="385" alt="2" src="https://user-images.githubusercontent.com/19389565/27765190-0acca9b0-5eb4-11e7-801a-dc38df6e6007.png">

**Comment by jeffyoung** [comment]
Hi @ivanklevin.  Thanks for trying out the extension!

I just pushed a change to the TFVC README file that talks about `.tfignore` files. Here's that [FAQ](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#many-files-are-showing-up-in-the-tfvc-viewlet-that-dont-show-up-in-the-visual-studio-ide-how-can-i-ignore-them). In this case, you'll want to set one up for this repository.  While it appears the folder you're showing was initialized at one point as a Git repository, you should be able to ignore those files with an entry like `\.git`. Other folders can be handled the same (and the linked FAQ has other links to the official documentation about `.tfignore` files).

**Comment by ivanklevin** [comment]
Thanks for the answer. About .tfignore is understandable. And what about the tree of changes? Displaying folders and subfolders, what would exclude or include several files at once?

**Comment by jeffyoung** [comment]
Displaying the list of files/folders in VS Code is something I believe is out of control of the extension.  The SCM provider gives the list of files to the SCM extensibility point and the UI is handled by VS Code.  That said, I agree it would be handy to collect all files under a particular folder in a collapsed tree node.

If you want to move multiple files from, say, Included to Excluded, you can multi-select the files you want to move, right-click on one of them and select the action to perform.

However, I think the best first step in your case is to set up a .tfignore file.  I'm going to guess that creating one will take care of most of those 29,815 files.  😄
