### ISSUE TITLE
A problem to connect to TFS

### ISSUE THREAD

**Issue by DavidOs55** [microsoft/azure-repos-vscode#279]
Hi,
I'm try to connect to TFS 2017 but i get a message that the vs code is offline
VS Code version : 1.13.1
VSTS version: 1.119.2
TFS version : 15.112.26307.0
OS : Win 7  64 bit

I did this steps:
1.  Install Visual studio Team Services Extension.
2.  Upload an angular2 project to a TFS location using vs studio 2015 and checked in all files
3. In the visual studio code : F1 > team signin > user name and password for TFS
4. The icon of Team in the bottom left still saying : I appears visual studio code is offline. Please connect and try again.
![vscode_tfs](https://user-images.githubusercontent.com/20335174/28063791-02a8b3b2-663b-11e7-87bf-cdc068bff750.png)

This is the log file 

[team-extension.txt](https://github.com/Microsoft/vsts-vscode/files/1138483/team-extension.txt)

**Comment by jeffyoung** [comment]
Thanks for trying out the extension @DavidOs55.

From the image you supplied, the message "TFS: settings.json has been automatically checked out for editing." wasn't added by the vsts-vscode extension.  Perhaps it was added by Ivan's extension?

The vsts-vscode extension *will* display a message regarding being offline if a connection to the TFS/VSTS server cannot be made. The error displayed in the dialog appears to be informing you that commands the vsts-vscode extension provides are being run when you aren't logged in to the server (or are unable to connect).  From the log file you provided, I see `Error: getaddrinfo ENOTFOUND tfs2017.vcloud.uk tfs2017.vcloud.uk:8080`.  If the extension tries to connect to the server, but can't, you will see errors.

Is the information contained in the following debug log line accurate? `Found a TFVC repository for url: 'http://tfs2017.vcloud.uk:8080/tfs/leyba.pki' and team project: 'CRL'.`  For some reason, the extension can't get an address for that server (tfs2017.vcloud.uk).

**Comment by Ne-Ne** [comment]
I have just tried this extension.

I too seem to have the same problem. It connects to TFS fine. However I cannot see any diff changes from the side bar.
