### ISSUE TITLE
VSTS installed but not available

### ISSUE THREAD

**Issue by jdrake3** [microsoft/azure-repos-vscode#280]
Though I have the VSTS Extension installed:

![vstsinstalled](https://user-images.githubusercontent.com/1247320/28088220-00e607b0-6653-11e7-9777-097acd57605d.png)

It is not available on the Switch SCM Provider list:

![vstsnotavailable](https://user-images.githubusercontent.com/1247320/28088168-d4f63bb6-6652-11e7-9343-21467e8869a2.png)

OS: Windows 10 Version 1511 (OS Build 10586.962)
VS Code: 1.14.0
Visual Studio Team Services: 1.119.2

**Comment by jeffyoung** [comment]
Have you run through the [Quick Start](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#quick-start) (there's some set up that you need to do)?  If so, can you [enable the debug log](https://github.com/Microsoft/vsts-vscode#logging) and see if there is an indication of any errors?
