### ISSUE TITLE
Add an indicator to show file has changed

### ISSUE THREAD

**Issue by stephen-nba** [microsoft/azure-repos-vscode#281]
I would like to be able to see that a file I am working on has changed (been checked out). Currently you can see this info on the source control panel but you have to switch to it. It would be better if there was an indicator say in the tab of the editor or something. Or it could be like Visual Studio where you get a little tick in the solution explorer next to the file. 

Also, it would be great to have a way to see the diff of the current file to the server, there doesn't appear to be any way to do this (TFVC)

**Comment by jeffyoung** [comment]
These are two great suggestions.  I'd need to investigate the first (adding some other indication to the VS Code UI).  I'll open a separate issue for the second (an additional diff option).
