### ISSUE TITLE
Grouping of included/excluded items

### ISSUE THREAD

**Issue by 72gm** [microsoft/azure-repos-vscode#283]
Instead of having a big massive list of items in included/excluded changes can they not be grouped by project/folder as they are in visual studio proper?

**Comment by scaillerie** [comment]
And exclude / include items by project / folder could be nice too :-)

**Comment by jeffyoung** [comment]
At this point, I believe having a Tree View in the SCM Viewlet is currently unsupported (it appears to be only supported in the Explorer viewlet; at one point I found an issue in the VS Code repository discussing this but can't seem to find it right now). Here are several related VS Code issues we'd need completed that would enable this support: https://github.com/Microsoft/vscode/issues/24460, https://github.com/Microsoft/vscode/issues/14582.  Once those were completed and exposed to the SCM providers, we should be able to improve this experience.
