### ISSUE TITLE
Add to Documentation: Changing Repository Mapping

### ISSUE THREAD

**Issue by largeDachshund** [microsoft/azure-repos-vscode#289]
I have multiple VSTS projects.  I'm sure there's a way to re-map to another repository.  I don't have the foggiest idea.  Documentation needs to be added for this scenario.

Thanks,

**Comment by jeffyoung** [comment]
Are you referring to the ability to edit your workspace mappings?  The VS Code extension doesn't have support for creating/updating/deleting workspaces but you can do so with the command line tool.  Here's the documenation for the [workspace command](https://www.visualstudio.com/en-us/docs/tfvc/workspace-command).

Let me know if you're referring to something else.
