### ISSUE TITLE
Feature Request: Code Review

### ISSUE THREAD

**Issue by dfrencham** [microsoft/azure-repos-vscode#292]
Hi. Is the team considering Code Review functionality as a future enhancement? That is currently the only reason my team needs to switch back and forth to Visual Studio.

**Comment by jeffyoung** [comment]
Hi @dfrencham.  Not at this time although I agree it would be a great addition.  Lots of thought around the user experience would certainly be necessary.  What would you think the experience would look like?

**Comment by dfrencham** [comment]
I'll see if I can mock something up. I'm not sure around the limitations of creating Code Review request/response work items via the TFS APIs (particularly associating comments with lines of code).

I'll research what is possible, then report back.

**Comment by Steveja74** [comment]
Hi @dfrencham .  How did you go looking into Code Review functionality?

**Comment by dfrencham** [comment]
@Steveja74 I didn't revisit it to be honest. My employer moved to git instead, and we manage our reviews via pull requests.

**Comment by stoianchoo** [comment]
Can this be done like in ```vscode-pull-request-github```
I think this is similar to #438

**Comment by yasin-fiserv** [comment]
Would really love to see this in the extension and agreed on @stoianchoo's suggestion. Considering Github is now MS, this should happen, hopefully soon.
