### ISSUE TITLE
Where to change Team server URL?

### ISSUE THREAD

**Issue by krishdeepak** [microsoft/azure-repos-vscode#308]
Hi Team,
I am getting 500 error while connecting to vsts. Initially I used VSTS Git repository for one of my project and later trying to connect to different project which is in TFS team services. Is there any option to change projects or VSTS URL in same account?

![image](https://user-images.githubusercontent.com/6876123/29885305-f9e11dbc-8dd3-11e7-81fc-f317e1318e1b.png)

Thanks,
Krish

**Comment by IanMoroney** [comment]
I am having the same problem as this and I can't find a single way to change the team server URL. It seems this functionality is missing, but I can't even find a configuration option to modify in a file either.

**Comment by IanMoroney** [comment]
@krishdeepak I found the issue and how to resolve it.
The GIT repository that you are working on, you need to change the remote path on your local git repository itself.
VSCode calls git, git sets the Remote path as the URL that you initially set into VSCode. 
VSCode then reads the Remote url every time it opens and checks to see if you are logged in or if the Git credential manager has creds for you. If not, it prompts for creds.
When you change the Remote url on the git repo itself, and relaunch code, it will read the new Remote URL and ask you to sign into there instead.
Confirmed as tested and working.
