### ISSUE TITLE
TFS TeamProjects containing "é" causes connection failure

### ISSUE THREAD

**Issue by RyM934** [microsoft/azure-repos-vscode#310]
When trying to connect to a TeamProject with "é" symbol in the name I get the following error. "The Team Services extension only supports TFS version 2015 Update 2 or later. Please verify your TFS server version." When connecting to other TeamProjects on the same server with standard characters in their name it connects fine and we are on TFS 2017. Debug information reveals that it fails right after this message. "Getting team project...  Url: 'http://XXXXXXX/', collection name: 'XXXXX', and project: 'Caf�s'." � = "é". server and company names have been masked with X. Could this be an encoding issue?

**Comment by RyM934** [comment]
This seems to be an issue with decoding stdout from calls to TF.exe. Would it possible to create a new setting where TF command io encoding could be specified? I'm getting the extension to work when I force the stdout to be decoded to LATIN1 in my case.

**Comment by emiltorp** [comment]
Exactly the same issue I reported yesterday ( #309 ). But this has more debugging information about encoding.
