### ISSUE TITLE
TFVC: Endless login attempts and error pop-up

### ISSUE THREAD

**Issue by d-dizhevsky** [microsoft/azure-repos-vscode#311]
I've got TFVC extension installed and initialized in VS Code but for some reason I'm not able to sing in. It is just keep asking me to do that over and over again, and also I'm not able to use any of the UI features (check-in, check-out, associate work item and so on). 
The only error I have is this VS Code pop-up:
`(team) You are signed out. Please run the 'team signin' command.`

Please note that I have successfully logged in via web browser and CLI (tee-clc) using same credentials.
I also tried to remove items from Keychain and re-try, re-install extension, type domain using login@domain format instead of domain\login.

Also there is pretty much nothing in team-extension.log (it doesn't exist at all), terminal and output.
The only thing happen when I try to sign in is these commands under the TFVC output:

`tf add -noprompt -?
tf workfold -noprompt ********
tf add -noprompt -?
Using TFVC command line: /usr/local/Cellar/tee-clc/14.123.0/bin/tf (14.123.0.201708301600)
tf status -noprompt -format:xml -recursive
`
and that's it.

User-settings I have:
`{
    "team.logging.level": "debug",
    "tfvc.location": "/usr/local/Cellar/tee-clc/14.123.0/bin/tf",
    "team.showWelcomeMessage": false
}`

Configuration:

- MacOS Sierra 10.12.6 (16G29)
- VS Code 1.15.1 (1.15.1)
- TEE-CLC 14.123.0.201708301600
- TSVS Extension v1.122.0
- TFS 2017 RTM

**Comment by DavidML3** [comment]
I am experiencing the same. Could this be a firewall issue?

**Comment by machintoshuser** [comment]
any fixes on this issue?

**Comment by d-dizhevsky** [comment]
@machintoshuser I haven't had a change to try to reproduce this issue on newest versions (if any)
also, unfortunately it seems like a dead repository
dunno if someone really going to fix something

**Comment by gauravthorath** [comment]
I am also getting same issue : **_(team) You are signed out. Please run the 'team signin' command._**
whenever I am trying to check in or out with VS Code. 

Any workaround will be appreciated.
