### ISSUE TITLE
TFVC Comment Not being passed to tf checkin command

### ISSUE THREAD

**Issue by dragoljub** [microsoft/azure-repos-vscode#312]
TFVC not not passing comment to tf command line and not allowing check in. This used to work before my latest VS Code update.

tf checkin -noprompt ******** D:\MyPyFile.py
[Checkin] TF10139: The following check-in policies have not been satisfied:   Provide a comment for the check-in.  No files checked in.

![image](https://user-images.githubusercontent.com/2701562/30235512-c0ec76c8-94bd-11e7-8cad-beb1365c960a.png)

**Comment by dragoljub** [comment]
Anyone Seen this Before? I'm Considering Downgrading VS Code Version.

**Comment by dragoljub** [comment]
I just tried latest VS Code Insiders and the VSTS extension checkin works correctly for this version of VS Code.

![image](https://user-images.githubusercontent.com/2701562/30296286-7fc8035a-96f8-11e7-9648-caafd1a3748e.png)

**Comment by Stompf** [comment]
I'm having the same problem with check-ins using the commit UI in VSCode 1.16. Comments are not getting passed.

**Comment by robinwit** [comment]
Same here, it's broken.

**Comment by nategreen** [comment]
+1

**Comment by robinwit** [comment]
I downloaded the previous version [here](https://code.visualstudio.com/updates/v1_15).

**Comment by TheCriticalPath** [comment]
+1

**Comment by bmarrufo** [comment]
I'm experiencing the same problem.
I'm able to check in my changes, but my comments are getting ignored.

**Comment by abdulkareemnalband** [comment]
Also sometimes this works
If i attach work-item then work item related comments is recorded but manually added/modified comment is not reflected in command line

**Comment by evakili** [comment]
I've same problem.

openSUSE 42.2 (x64), VSCode 1.16.0, extension 1.122.0

**Comment by knegg** [comment]
Same problem here. Full description [here](https://stackoverflow.com/questions/46488285/commit-message-not-showing-up-after-commit/46520051#46520051)
Hope this issue will be fixed in the next update.

**Comment by diaodiaop** [comment]
3 years later,Have you found a solution to this problem?
