### ISSUE TITLE
Cannot read property 'syncType' of undefined

### ISSUE THREAD

**Issue by daniefer** [microsoft/azure-repos-vscode#323]
I get the following error from vscode when I attempt to sync.

> Error (team) Cannot read property 'syncType' of undefined

Here is the console output. Is there a log file somewhere I can also upload?

```tf add -noprompt -?
Using TFVC command line: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe (15.117.26830.0)
tf status -noprompt -collection:https://server/tfs/collection ******** -format:detailed -recursive
tf resolve -noprompt ******** c:\src -recursive -preview
tf get -noprompt ******** -nosummary c:\src -recursive
tf status -noprompt -collection:https://server/tfs/collection ******** -format:detailed -recursive
tf resolve -noprompt ******** c:\src -recursive -preview
tf status -noprompt -collection:https://server/tfs/collection ******** -format:detailed -recursive
[Sync] Cannot read property 'syncType' of undefined
tf resolve -noprompt ******** c:\src -recursive -preview

**Comment by yashv** [comment]
You can enable logging to a file (team-extension.log: created in the same folder as your repo) by opening settings and providing a value for "team.logging.level" property.

![image](https://user-images.githubusercontent.com/1425452/32036513-0081900a-b9e6-11e7-9e2a-6e1073f30b7e.png)

**Comment by txavier** [comment]
Was this ever resolved.  I am continuously having the same problem.

**Comment by tralawar** [comment]
@txavier  this happens to me when I add a file and then change it by removing/deleting/renaming/moving it. 

TFS sometimes has trouble tracking these changes, especially it you add a file outside of VSCode using the explorer.

When I open my changes in Visual Studio I can see it is trying to add a file which doesn't exist anymore, hence, "[Sync] Cannot read property 'syncType' of undefined". Undo the add file change of the nonexistent file.
