### ISSUE TITLE
ETIMEDOUT 104.214.111.103:443 error

### ISSUE THREAD

**Issue by siliond** [microsoft/azure-repos-vscode#324]
@jeffyoung I'm getting a ETIMEDOUT 104.214.111.103:443 error, being behind a proxy configured via environmental variables, log 
[team-extension.log](https://github.com/Microsoft/vsts-vscode/files/1356944/team-extension.log)

Please advise.

**Comment by Lowestkillcount** [comment]
Same issue - https://github.com/Microsoft/vsts-vscode/issues/319 

The ip for your VSTS site seems to be fairly static - i've had to resort to adding an exception to the proxy and allowing through the firewall directly

**Comment by svendebaets** [comment]
Is there really no other solution than directly going through the firewall? Our security and network teams will never agree with this. Thanks for any pointers on how to configure the proxy in VS Code. 

We tried configuring http.proxy but without success.
When I look around, I find two approaches to configure a proxy in VS Code. One is to configure http.proxy in the VS Code settings. Another is to configure a proxy on Chromium. Which one is the correct approach?
