### ISSUE TITLE
Wrong encoding team project name

### ISSUE THREAD

**Issue by wagnerlduarte** [microsoft/azure-repos-vscode#328]
When I have a project that the `_teamProjectName `contains sharp accent, any actions I do the plugin show the message **(team) You are signed out. Please run the 'team signin' command.**.

![image](https://user-images.githubusercontent.com/17439470/31780004-4f714164-b4d3-11e7-8a57-7388925dedbd.png)

![image](https://user-images.githubusercontent.com/17439470/31780267-05c2da86-b4d4-11e7-9803-c81226e0a6a9.png)

But if I connect in TFS repository where the project name don't has sharp accent the plugin works perfectly.

I saw a letter with strange encoding at log that made me come to this conclusion.
[team-extension.log](https://github.com/Microsoft/vsts-vscode/files/1399045/team-extension.log)

For fix around this problem, we rename Team Project with name without sharp accent.
Is it possible verify this problem for we could use Team Project Name with sharp accent and other accents?

**Comment by machintoshuser** [comment]
I am still experiencing the same. Any fix on this?

**Comment by wagnerlduarte** [comment]
Hi @machintoshuser !
I resolved removing the accentuation in the name of my Project Name.
This error ocurred because this plugin works only with english names in the Project Name.
I live in Brazil and unfortunately my project's name had accentuation.
Just rename the project that can work for you too.
