### ISSUE TITLE
I was signed out automatically

### ISSUE THREAD

**Issue by al-wys** [microsoft/azure-repos-vscode#331]
I opened a TFS repository, and I signed in via command "team: signin". Then I tried to open an file from "Included Changes" like below:
![image](https://user-images.githubusercontent.com/16317690/32305924-3c726b70-bfb3-11e7-9d47-ea62d4666504.png)

After that, this notification was prompted:
![image](https://user-images.githubusercontent.com/16317690/32305887-0d09ce00-bfb3-11e7-8859-9515dec6dc31.png)

But I could work with the TFS server normally in Visual Studio 2015.

**Comment by dmumladze** [comment]
I think the issue is only relevant to TFS that needs NTLM authentication as the current Node module they use has bugs. Can someone from the vsts-vscode team comment about the issue?

**Comment by blakazulu** [comment]
having the same issue here
