### ISSUE TITLE
vsts-cscode getting the wrong Project over VSTS

### ISSUE THREAD

**Issue by LeanLL** [microsoft/azure-repos-vscode#335]
Hi there! I have a VSTS account (https://XXXXX.visualstudio.com/). Inside this Account, I have a lot of projects. When I open a project over vscode, the 'Team Project indicator' is not show me the right name of the project.

Am I doing something wrong?

**Comment by kaylangan** [comment]
@LeanLL when you say it's not showing you the right project name--are you saying that the active repo actually belongs to a different project than the one displayed?

**Comment by LeanLL** [comment]
@kaylangan Exactly! am I missing something?
