### ISSUE TITLE
Feature Request: Team Sign-in support for multi-root workspaces

### ISSUE THREAD

**Issue by Blackbaud-ShaydeNofziger** [microsoft/azure-repos-vscode#339]
I have 20+ git repos I interact with, many times working across the code bases daily. I currently make use of a workspace containing all of these repos so I can easily switch between them without opening a new editor screen.

Now that multi-root workspaces are a stable released feature, it would be nice if this extension were updated to look at the context for which SCM provider is selected, and use that to connect to VSTS, as opposed to just looking at the base directory opened in vscode for the git repo.

**Comment by nonameolsson** [comment]
I just got the same issue. Love the Workspace feature in VS Code. But now I can't use VSTS Vscode anymore.

**Comment by Blackbaud-ShaydeNofziger** [comment]
@nonameolsson for now, my workaround is to use multiple windows of vsts, and switch between them. Obviously I'd rather the VSTS extension use the context of which multi-root workspace is selected, but there's definitely workarounds that can allow you to keep using VSTS/VSCode

**Comment by 123dev** [comment]
Not sure if it is the same issue.
It appears that I can only have token for a single VSTS .

We have both work and personal accounts, and some repos are in one whereas others in the other.
How can I configure this plugin so that it uses the proper credentials with each?

Thanks

**Comment by ImperfectSeven** [comment]
I ran into this issue when trying to us the "Create Pull Request" command. That command should key off of my active repo, but when in a multi-root workspace it appears to only capture the first repo as my active repo.

**Comment by JustinGrote** [comment]
I have @ImperfectSeven's issue as well. The way this should work is based on which repo I have selected either as my current active open file, or currently selected source control, it should switch repositories. Currently it always shows whatever is listed as my first repo in my workspace at the bottom no matter how I attempt to navigate to another repo.

![image](https://user-images.githubusercontent.com/15258962/48164149-8b02fa00-e296-11e8-80d5-58b28945e1a2.png)

**Comment by jRichardeau** [comment]
Any news for this feature ? This is a very huge constraint to use multi-root workspace.

**Comment by JustinGrote** [comment]
At the very least, add a vscode command to switch workspaces. Would work like this:
Name the command something like Team:Select Workspace Repository...
Then show a list of folders in the workspace
When I select one, call the routine to switch the plugin to the selected workspace, as if I did an Open Folder.
From there then it's just a matter of hooking it to some event to do it automatically.
