### ISSUE TITLE
Feature request: Basic auth support

### ISSUE THREAD

**Issue by guillaume86** [microsoft/azure-repos-vscode#340]
I was able to hack it in by replacing line 31 by line 36 in here https://github.com/Microsoft/vsts-vscode/blob/fde825590016647e7f509fd65c0ef58d87976537/src/info/extensionrequesthandler.ts#L36 but a proper option would be better.

I can try to submit a pull request if necessary but it's probably a 5 mins job for someone already familiar with the extension API.

**Comment by guillaume86** [comment]
Would a PR be accepted for this?

**Comment by guillaume86** [comment]
Would this be accepted if I submit a pull request to add the parameter? `forceBasicAuth` ok for the parameter name?

**Comment by ermeckle** [comment]
A pull request would be welcome.  I assume you've considered using a PAT instead of basic auth?

**Comment by guillaume86** [comment]
Thanks I'll try to submit one. Yes my company is stuck on TFS 2015 on premise (no PAT support).

**Comment by guillaume86** [comment]
Pull request is here: https://github.com/Microsoft/vsts-vscode/pull/388
