### ISSUE TITLE
VSCode - SignIn Error

### ISSUE THREAD

**Issue by atulkumar** [microsoft/azure-repos-vscode#342]
Hi 

I am configuring VS Code with tfvc but I am getting error while running Team:sign command.Can you help me to fix this?

Error details -
_Error (team) No Team Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder..._

Steps -
File - > Open folder(with Repo) ->Run Team SignIn command

FYI,Extension is installed and UserSettings file is updated with tf.exe location
and I am able to Checkout/ChecnkIn from Visual Studio 2017 from same folder location and if I modify any file in folder I can see updates in Source Control Explorer.

Version Details -
VS Code - 1.18.1(Latest)

Thanks in advance!

**Comment by ehanlon** [comment]
I'm encountering this issue as well. I'm wondering if it has to do with the [new URL format for SSH](https://docs.microsoft.com/en-us/vsts/git/use-ssh-keys-to-authenticate).

Although, they did complete #334 two weeks ago to fix that.

**Comment by atulkumar** [comment]
Ok.Are you able to find the solution?

I am using TFS so what to do for SSH key in this case?
