### ISSUE TITLE
Cannot rename files in vscode

### ISSUE THREAD

**Issue by Fralleee** [microsoft/azure-repos-vscode#347]
Can't rename files in vscode, is there something I'm doing wrong?

Original name
![image](https://user-images.githubusercontent.com/6375613/33381741-1fcd8532-d51f-11e7-941c-4b8c41e95e8c.png)

Context menu options:
![image](https://user-images.githubusercontent.com/6375613/33381821-5b75408e-d51f-11e7-831c-9c8fba202df1.png)

Renamed
![image](https://user-images.githubusercontent.com/6375613/33381751-29f66aa6-d51f-11e7-8cad-167e9747e569.png)

Result in visual studio:
![image](https://user-images.githubusercontent.com/6375613/33381770-3a1fcaf8-d51f-11e7-9284-23044590f779.png)

Stackoverflow question: 
https://stackoverflow.com/questions/47568965/cant-rename-files-correctly-in-vscode-with-vsts

**Comment by marpstar** [comment]
This seems like it's more of an issue with your project. With Visual Studio projects, sometimes they're configured to specify each individual file of the project. This means that when you rename a file without updating the project file, it won't work. TFVC isn't what makes this happen in Visual Studio. It's Visual Studio knowing how to update those project files.

**Comment by RihardsVla** [comment]
The problems is that at least for me Azure repos are missing TFVC comman tfvc.Rename.

**Comment by petrinecp** [comment]
Same issue here. The [documentation](https://github.com/Microsoft/azure-repos-vscode/blob/master/TFVC_README.md#file-explorer) clearly shows there should be Delete/Rename (TFVC) entries in the file explorer's context menu.
![image](https://user-images.githubusercontent.com/5637849/50766801-e2afe880-127a-11e9-84a5-0fda7c6d59b4.png)

**Comment by wilhelmer** [comment]
Same issue here.

**Comment by odravison** [comment]
I'm facing the same issue here.

**Comment by MateoOlarteCampo** [comment]
Maybe the file is being used by another program. In my case I was running the server using the root directory.

**Comment by tibinthomas** [comment]
game issue for me too.
