### ISSUE TITLE
cannot logout user

### ISSUE THREAD

**Issue by rupppat** [microsoft/azure-repos-vscode#348]
I had to change the user on a VSTS project. Everytime I open the project in VS Code the old user is used and I get an error. I tried to delete the project folder and recreacte it from Source Control Explorer. See the attached log:
[team-extension.log](https://github.com/Microsoft/vsts-vscode/files/1527816/team-extension.log)

**Comment by mikaoelitiana** [comment]
For Mac, I found a way to fully disconnect. You have to open the Keychain Access app and find a key starting with `team:...`. You can delete this key and after restarting VSCode, you should no longer be connected.
