### ISSUE TITLE
Feature Request: Support Server workspaces

### ISSUE THREAD

**Issue by clisc** [microsoft/azure-repos-vscode#356]
There were some indirect topics on this, but I didn't see a direct request for this, so I'm creating this one now.

I work on a large team on a server workspace and would love to have Code interact with my TFS server and check things out automatically like Visual Studio does.

Thanks!

Edit:
#176 
This is the one I was thinking of but it appears to be more of a doc defect than a request for server support.

**Comment by saqibn** [comment]
when can we expect an update on this?

**Comment by kaylangan** [comment]
@saqibn this is a great feature request. It's on our backlog, but we currently do not have plans to address it in the upcoming 6 months.

**Comment by AlexisColes** [comment]
Please could you rethink the priority on this, we are quite a loyal Microsoft shop and use tfs, local work-spaces do not seem to work very well and it is making using VS Code very difficult for us.

Is is like we are being punished by Microsoft for using Microsoft products!

**Comment by SJasinski** [comment]
Still (im)patiently waiting on this :-)

**Comment by DennisD2** [comment]
The same at my site (large financial company with dozens of large applications). 
We use both TFS and git and are in the situation of using VSCode more and more. While the git support in vscode is excellent, the current need to have local workspaces and the resulting slowness is close to a showstopper (not for vscode, but for TFS). I have a workspace already stripped down to ~65K (90% .tfignored) files, and after changing a file it lasts 45 seconds until vscode displays it as 'modified'. Same time for checking in. The same task with server-side workspace needs less than 5 seconds.

**Comment by gmurray81** [comment]
I think we can't even create local workspaces for our project. Too big. Get error messages when I try to switch a workspace to local. So can't use TFVC with Code

**Comment by mattdkerr** [comment]
@DennisD2 - this may not be a usable work-around for some, but personally I have used GitTFS https://github.com/git-tfs/git-tfs to interact with a project and not have to worry about checking things out so much.

**Comment by masha6** [comment]
Any updates about this? An important feature for enterprise environments.

**Comment by bemaxima** [comment]
I'm waiting too.

**Comment by dmytro-lymarenko** [comment]
Any news about server workspaces?

**Comment by kaylangan** [comment]
At the moment we do not have plans to add support for server workspaces.
