### ISSUE TITLE
It seems not to support TFS version 2017

### ISSUE THREAD

**Issue by xufengzi** [microsoft/azure-repos-vscode#357]
The Team Services extension only supports TFS version 2015 Update 2 or later. Please verify your TFS server version. Connecting TFS version 2017 to the wrong

**Comment by rkralston** [comment]
I am getting the same error use this executable:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe (15.129.27725.3)`
`Using TFVC command line: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe (15.129.27725.3)
tf status -noprompt -format:detailed -recursive`

**Comment by whoisj** [comment]
@rkralston if you're seeing issues with TF.exe (shipped with Visual Studio) you should report them on https://developercommunity.com/

**Comment by whoisj** [comment]
> That link has an invalid certificate from a wonky issuer.

I've updated my comment with the correct link. My apologies 😖

**Comment by rkralston** [comment]
Noice.

I'll put the comment there. However, I'm not sure it is an issue with TF.exe. Have you tested this against v2018r2?
