### ISSUE TITLE
VSTS is not listed as an SCM provider

### ISSUE THREAD

**Issue by hughanderson4** [microsoft/azure-repos-vscode#360]
Trying to get started with VSTS in VS Code.
Following the instructions [here](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#quick-start) i get to the last step but i always fail at "Set the SCM Provider to TFVC. Read how..."

in the Source Control View when i click the ... the only option is "Install SCM Providers" and this takes me to the Extensions list where VSTS is listed and installed.

in the footer of VS Code i can see that i am signed in to my TFS local workspace (it was converted from Server workspace which took a long time but successfully completed).  links in VS Code footer function correctly to take me to my TFS website etc.

please help to use VSTS as my SCM provider in VS Code.

**Comment by NanFengCheong** [comment]
@hughanderson4 I dont think you need to manually set. Are you opening the root folder of your workspace?

**Comment by jimutt** [comment]
I'm experiencing the same issue using the plugin with VSCode 1.20.1. I've been trying with different local workspaces (both those with a single working folder as well as some with multiple). 

The plugin seems to be logging the following error though:
2018-03-06T10:53:51.187Z - error:  [204620] Caught an exception during Tfvc SCM Provider initialization
2018-03-06T10:53:51.188Z - error:  [204620] Cannot read property 'replace' of undefined

**Comment by chris-eaton** [comment]
I am having the same issue... Also.. Everyone keeps saying "open your workspace"... what if you dont have a workspace.. because its in TFS.. and you need to connect to TFS to get access to your workspace?

So far VSCode has been a terrible experience compared to VS2017. Surely connecting to Microsofts own source control should be an easy experience for VSCode?

**Comment by DalpheSDC** [comment]
We are trying the same but getting same issue, not problem connecting to the team project from VS code but when we open the TFVC workspace it doesn't seems to react on it in the SCM Explorer, can any one tell me why, we are running in a TFVC local workspace have event try just to make a standalone Collection to see it there were any setting issue on the Collection. but still no Lock.

**Comment by DalpheSDC** [comment]
Just to mention we are using TFS 2018 update 2

**Comment by springjazzy** [comment]
I'm having the same issue. I've even managed to connect to out local TFS server so that I can see project and builds but switching from git to VSTS is above impossible. I've no idea how to check-in files to local VSTS using that extension.
