### ISSUE TITLE
TFS is not detecting any add/delete/rename file/folder from Vscode

### ISSUE THREAD

**Issue by rupeshtiwari** [microsoft/azure-repos-vscode#362]
TFS is not detecting any add/delete/rename file/folder from Vscode.
I am trying to add or delete file once I do that TFS is not detecting and in pending changes it is not showing up. TFS 2017 with latest VSCode 1.19.1, 64 bit

**Comment by ScottAHoward** [comment]
I too am having this issue.

**Comment by kksevta** [comment]
+1

**Comment by roopkt** [comment]
I end up using visual studio for any file add / delete and rename operation. But it is pain to switch between editor. I love to work with VSCode but i have to remember when I am doing any file operation then switch to VS. 
I hope like VSCode has native support for GIT similarly it should work with TFS

**Comment by tinynow** [comment]
+1

**Comment by sunil233** [comment]
Me too am having this issue.Any update on this?

**Comment by andreaci** [comment]
same problem here.
adding a file in vscode doesn't add file in TFS

**Comment by jRichardeau** [comment]
Is this issue going to be resolved ?

**Comment by oferah** [comment]
Same here using win 7, vscode v1.32.3, Azure Repos v1.149.2

**Comment by adam-marshall** [comment]
Same here, this _was_ working for me, and now it isn't. 

I've had it when adding a component via angular CLI, one of the files appears in 'excluded changes', the others do not appear at all. I cannot see what is causing it.
