### ISSUE TITLE
Error: command 'team.signin' not found

### ISSUE THREAD

**Issue by walrus95** [microsoft/azure-repos-vscode#371]
Greetings, I'm getting an error message when trying to setup the Visual Studio Team Services extension for Visual Studio Code:

`command 'team.Signin' not found`

I'm running the following versions:
- Visual Studio Code 1.20.1
- Visual Studio Team Services 1.122.0
- Windows 10

I navigate to a folder containing my project in the Windows Command Prompt. I'm able to successfully run `tf worldfold` in this folder. I then open up this folder in VSCode.

I press Ctrl-Shift-P in VSCode and type in `Team: Signin`, giving me the error message above. I have not been able to enter my PAT yet into VSCode.

Thank you!

**Comment by b-e-n-j** [comment]
Is the path to TF.exe in VS Code's user settings the same as when you run `tf workfold`?
I had the same problem when I configured VS Code with the path to VS2015's TF.exe, but the workspace had been created in VS2017.

**Comment by walrus95** [comment]
Yes, they're the same. My path is:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer

I used to have "TF.exe" included in my path in VS Code, but I removed it, and it still doesn't work. I'm still seeing the same problem as described above.

Any other ideas?

Thanks again.

**Comment by chrisdias** [comment]
The error you are getting (`command: 'team.Signin' not found`) indicates that the extension is properly loading. To diagnose the problem, you can open the Dev Tools and let us know what you see in the console (there should be errors).

In VS Code, please do the following:
* Press `F1` and then search for `Developer: Toggle Developer Tools`
* Once the tools are opened, click on `Console` and then see if there are any errors listed. Having this information will help us diagnose the problem, so please post them here.

From there, you may have to do a "hard" uninstall and reinstall of the extension.  If you are on the latest VS Code (version 1.21.0) you can do the following:

* Press `F1` and search for `Developer: Reinstall extension...`
* Choose the VSTS extension from the list
* Fully shut down and then restart VS Code
* Reinstall the extension from the marketplace

**Comment by walrus95** [comment]
Greetings Chris!

Following your steps, I have captured the output from the console, and have included the output below. 

Interestingly, since I first posted this issue to GitHub, my company has created a separate branch of our project using TFS. I have both branches in separate directories on my computer, both the old branch and the new branch. I'm still experiencing the same issue as described previously on the old branch, but in the new branch, I'm experiencing a different error message when I do a Ctrl-Shift-P and execute "Team: Signin." I will describe the new error message in the new branch later on in this post.

Note, that I'm able to run successfully `tf workfold` in both branch directories, for the following output:

```
Workspace : SOMENUMBERS  (Walrus95)
Collection: http://servername:8080/tfs/companyname
 $/path/to/oldfolder: C:\proj\oldfolder
 $/path/to/newfolder: C:\proj\newfolder
```

In the old branch, as mentioned previously, I'm still expericing the same problem as described in my previous post. Here's the output from the console:

```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:257
   [Extension Host] Activating
   extension `ms-vsts.team` failed:  undefined is not iterable
   t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:257

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2842
   Activating extension 'ms-vsts.team' failed: undefined is not iterable.
   O._logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2842

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:257
   [Extension Host] Here is the error stack:  TypeError: undefined is not iterable
      at ExtensionManager.<anonymous> (C:\Users\walrus95\.vscode\extensions\ms-vsts.team-1.122.0\out\src\extensionmanager.js:348:47)
      at Generator.throw (<anonymous>)
      at rejected (C:\Users\walrus95\.vscode\extensions\ms-vsts.team-1.122.0\out\src\extensionmanager.js:9:65)
      at <anonymous>
```

The when I do a Ctrl-Shift-P and execute "Team: Signin" I get an additional error in the console, saying:

```
notificationsAlerts.ts:39
   command 'team.Signin' not found
      e.onDidNotificationChange @ notificationsAlerts.ts:39
      (anonymous) @ notificationsAlerts.ts:28
      e.fire @ event.ts:142
      e.notify @ notifications.ts:127
      e.error @ notificationService.ts:58
      t.onError @ commandsHandler.ts:326
      (anonymous) @ commandsHandler.ts:311
      done @ winjs.base.raw.js:1391
      v @ winjs.base.raw.js:1237
      enter @ winjs.base.raw.js:914
      _run @ winjs.base.raw.js:1081
      _chainedError @ winjs.base.raw.js:1044
      n @ winjs.base.raw.js:749
      then @ winjs.base.raw.js:1449
      enter @ winjs.base.raw.js:760
      _run @ winjs.base.raw.js:1081
      _setCompleteValue @ winjs.base.raw.js:1065
      g @ winjs.base.raw.js:1183
      enter @ winjs.base.raw.js:865
      _run @ winjs.base.raw.js:1081
      _completed @ winjs.base.raw.js:1049
      l @ winjs.base.raw.js:1826
      n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ winjs.base.raw.js:1851
      g @ winjs.base.raw.js:1183
      enter @ winjs.base.raw.js:865
      _run @ winjs.base.raw.js:1081
      _completed @ winjs.base.raw.js:1049
      g @ winjs.base.raw.js:1183
      enter @ winjs.base.raw.js:865
      _run @ winjs.base.raw.js:1081
      _completed @ winjs.base.raw.js:1049
      e.resolveOk @ lazyPromise.ts:65
      e._receiveReply @ rpcProtocol.ts:135
      e._receiveOneMessage @ rpcProtocol.ts:96
      (anonymous) @ rpcProtocol.ts:33
      (anonymous) @ rpcProtocol.ts:213
      e.fire @ event.ts:142
      (anonymous) @ ipc.net.ts:81
      emitOne @ events.js:96
      emit @ events.js:191
      readableAddChunk @ _stream_readable.js:178
      Readable.push @ _stream_readable.js:136
      onread @ net.js:560
```

In the new branch my company just created, I'm experiencing a different issue. I don't understand why I experience a different problem depending on which branch directory I launch Visual Studio Code on. Here in the new branch I see in Visual Studio Code a popup saying:

```
(team) Unable to find the TF executable. Please ensure TF is installed and the path specified contains the filename. Provided path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
```

In the console, I see:

```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2207
   (team) Unable to find the TF executable. Please ensure TF is installed and the path
   specified contains the filename. Provided path: C:\Program Files (x86)\Microsoft
   Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
   e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2207
```

And when I do a Ctrl-Shift-P and execute "Team: Signin" in the new branch, I get an additional error in the console, saying basically the same thing:

```
notificationsAlerts.ts:39
   (team) Unable to find the TF executable. Please ensure TF is installed and the path
   specified contains the filename. Provided path: C:\Program Files (x86)\Microsof
   Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
      e.onDidNotificationChange @ notificationsAlerts.ts:39
      (anonymous) @ notificationsAlerts.ts:28
      e.fire @ event.ts:142
      e.notify @ notifications.ts:127
      e.notify @ notificationService.ts:62
      e._showMessage @ mainThreadMessageService.ts:86
      e._showMessage @ mainThreadMessageService.ts:47
      e.$showMessage @ mainThreadMessageService.ts:41
      e._doInvokeHandler @ rpcProtocol.ts:174
      e._invokeHandler @ rpcProtocol.ts:159
      e._receiveRequest @ rpcProtocol.ts:108
      e._receiveOneMessage @ rpcProtocol.ts:90
      (anonymous) @ rpcProtocol.ts:33
      (anonymous) @ rpcProtocol.ts:213
      e.fire @ event.ts:142
      (anonymous) @ ipc.net.ts:81
      emitOne @ events.js:96
      emit @ events.js:191
      readableAddChunk @ _stream_readable.js:178
      Readable.push @ _stream_readable.js:136
      onread @ net.js:560
```

Thank you for the suggestion of doing a "hard" uninstall and reinstall of the extension. However, this seems to have had no effect, and the error messages are still the same in both branches.

**Comment by chrisdias** [comment]
OK, it looks to me like in the first case the extension is throwing an error in the `activate` method and in the second case there's a path problem (but something is different such that the `activate` method is not throwing).

**Comment by sumithicom** [comment]
Hi @chrisdias,

I am facing the same problem. 
Can you please update on the above issue? or ssuggest any workaround for this?

Thanks in Advance

**Comment by ewekansige** [comment]
Workaround:
After installing the plugin, there will be a notification about the installation successfully completed. 
In the notification push the "Learn more..." button, a website will be opened but you can just close it. 

After this procedure you will be able to use the "team signin" command.

**Comment by mesari** [comment]
working well, thank you @ewekansige !

**Comment by Hopfenspirger** [comment]
Oh man, that was the same problem for me. I had to click once the "Learn more…" Button and than the Extention started to work. The last couple of hours I just closed the message or clicked the "Setup TFC Support Button" and were reading the docs and trying to get this to work but the Extention was not working at all. 

This should definitely be fixed…

My VS Code Version: 1.42.1
Installed Azure Repos Version: 1.161.0

**Comment by sgrips** [comment]
> Workaround:
> After installing the plugin, there will be a notification about the installation successfully completed.
> In the notification push the "Learn more..." button, a website will be opened but you can just close it.
> 
> After this procedure you will be able to use the "team signin" command.

Perfect !!!!!!

**Comment by nrogoff** [comment]
Thanks. I tried everything, but finally hit the work around / bug!

The answer for me was to click on 'Learn More...' on the initial setup message and everything started working as it should. I was then able to use the 'Team:Signin' command no problem.

It's taken me days to finally get it working. Some blocking bug there.

**Comment by jaypatrick** [comment]
> Workaround:
> After installing the plugin, there will be a notification about the installation successfully completed.
> In the notification push the "Learn more..." button, a website will be opened but you can just close it.
> 
> After this procedure you will be able to use the "team signin" command.

This worked for me as well, on VS Insiders w/ latest TFVC extension. Weird that you have to click the "Learn More..." button first, would have never figured that out on my own.

**Comment by okayfine** [comment]
> Thanks. I tried everything, but finally hit the work around / bug!
> 
> The answer for me was to click on 'Learn More...' on the initial setup message and everything started working as it should. I was then able to use the 'Team:Signin' command no problem.
> 
> It's taken me days to finally get it working. Some blocking bug there.

can confirm works for me too. I really hope this get fixed.
OS: OS X Catalina
