### ISSUE TITLE
VSTS is not detected when cloning via SSH

### ISSUE THREAD

**Issue by Kurtz1993** [microsoft/azure-repos-vscode#374]
I use to clone my Git repos using SSH. These repos are hosted in VSTS, but I found that when cloning via SSH nothing appears in the status bar and I cannot do any team operation because no repo was found.
![image](https://user-images.githubusercontent.com/5412470/36548524-1e247ac2-17b6-11e8-8639-89798767d863.png)

![image](https://user-images.githubusercontent.com/5412470/36548518-18ba334c-17b6-11e8-9235-60820abcd899.png)

It seems that the VSTS repository is only detected when working with https-cloned repositories. The image below is from another Git repository I have under the same team project.
![image](https://user-images.githubusercontent.com/5412470/36548588-4fdc2286-17b6-11e8-993e-04d3f7a9e601.png)

**Comment by nonameolsson** [comment]
Thanks for reporting thing! I have exactly exactly the same issue!

**Comment by kaylangan** [comment]
I suspect this may be due to the change in the SSH URL format and may be addressed by #334

**Comment by Kurtz1993** [comment]
Thanks for the response @kaylangan hopefully it does, and it will released soon 😃

**Comment by diegoortizmatajira** [comment]
I'm suscribing to this issue, I have the exact same problem, because I use SSH authentication when cloning on VSCODE and GitKraken

**Comment by nonameolsson** [comment]
What is the status on this? We really want to use this extensions at work.

**Comment by kaylangan** [comment]
@nonameolsson we have a release coming imminently. @ermeckle will have an update soon.

**Comment by jasterba** [comment]
Yup, having same issue.
I prefer using ssh, but team extension works only via http.

**Comment by kaylangan** [comment]
@jasterba can you try updating the plugin to v1.133.0 (released 4/3/18)? Does that fix the issue for you?

**Comment by johnib** [comment]
This issue is still opened, as the URLs have changed again.
Now when you clone the repo using SSH -- then the beginning of the URI used to be `git@...`.
The new format puts the name of the VS account instead of the git: `jorub@...` and this fails in the regex:

https://github.com/Microsoft/azure-repos-vscode/pull/407/files/69f1c64ef6364532c04c3cfd398e569bf3177fce#diff-12fcd6f5a5451abf874388911022d0fdR28

**Comment by hammady** [comment]
Any update on this issue? I'm still experiencing problems where my ssh repos are never detected.

**Comment by hammady** [comment]
Fortunately, if you replace back the ssh username to `git` it will work, and your git URL will still be valid to Azure.

**Comment by fabianem** [comment]
I am subscribing to this issue, too. Experiencing the same problem with ssh.
Any plans regarding this problem? The manual ssh username change to `git`, mentioned by @hammady, is a proper workaround.

**Comment by sXe79** [comment]
Hi, same issue here, any news?

**Comment by johnib** [comment]
What's the URI you used for cloning?


Jonathan​​​

________________________________

**Comment by sXe79** [comment]
Got from Azure Dev Ops: git@ssh.dev.azure.com:v3/User/Project/Repo

**Comment by johnib** [comment]
Looks good to me. for me it works perfectly using this format.
Weird.


Jonathan​​​

________________________________

**Comment by sXe79** [comment]
Yep, weird. Https works good... :(
