### ISSUE TITLE
Error: Unable to validate the collection assuming 'DefaultCollection'

### ISSUE THREAD

**Issue by Shadadam** [microsoft/azure-repos-vscode#376]
Hi, 
I'm getting this error: "Unable to validate the collection assuming 'DefaultCollection'."
Setup and Team:Signin seems to be fine. Did also set the local workspace.

Does anyone have any idea about this error message?

Thank you!

**Comment by JeffWeinreich** [comment]
+1

**Comment by ozvilok** [comment]
I am also getting this same error message.  

Prior to this it was telling me "It appears you are using a Server workspace. Currently, TFVC support is limited to Local workspaces." even while using a Local workspace.  After attempting the fixes described in [#325](https://github.com/Microsoft/azure-repos-vscode/issues/325) I started receiving the "Unable to validate the collection assuming 'DefaultCollection'" error.

Visual Studio Code : 1.33.1
Visual Studio 2017 & 2019
