### ISSUE TITLE
Audiology Accessibility

### ISSUE THREAD

**Issue by YRM64** [microsoft/azure-repos-vscode#380]
I attempted to listen to the video (the walk through of the Team Services Extension for Visual Studio Code).  I couldn't hear it.  I turned up the volume on my pc to maximum; turned up the volume on the actual video to maximum, and still couldn't hear it.  I'm in Starbucks surrounded by people (talking), and music playing in the background.  If I leave and go elsewhere, I can encounter the same situation.

I can go outside but then I can't plug into a power source, and the noise of traffic, sirens, automobiles, and environmental conditions pose significantly the same risk or dilemma.

This feature request involves providing the same video maximizing the volume on the above stated video on your end, if at all possible.  Thanks for your prompt attention to this matter.

Respectfully,
Yvonne R McGinnis
YRM64
The Purple Rose

**Comment by kaylangan** [comment]
@YRM64 can you provide me with the link to the video to which you are referring?

**Comment by YRM64** [comment]
All docker videos can't be heard in Starbucks.  There are people visiting, talking, and music playing in Starbucks.  I can't hear any of these docker videos.

**Comment by kaylangan** [comment]
@YRM64  can you please provide the link(s) to the video(s) to which you are referring?
