### ISSUE TITLE
(team) It appears you are using a Server workspace. Currently, TFVC support is limited to Local workspaces.

### ISSUE THREAD

**Issue by souravprakashjena** [microsoft/azure-repos-vscode#382]
While integrating TFS in  visual studio code i am getting this issue  @jeffyoung

**Comment by mpoelman** [comment]
Unfortunately, this is requested for quite a while (#176, #356), I really hope this gets more attention.

**Comment by souravprakashjena** [comment]
@mpoelman  i am using my Local workspace but still getting this error

**Comment by souravprakashjena** [comment]
Let me try once

**Comment by souravprakashjena** [comment]
i am getting this error

**Comment by rugpanov** [comment]
@souravprakashjena, please, ensure you have a path to the tf.exe util among your %PATH% environment variables.
If you have MS Studio 2017 then tf.exe should be at "...\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\"

**Comment by souravprakashjena** [comment]
i already set it on environment variables.Just have a look.
![untitledd](https://user-images.githubusercontent.com/13752535/38133784-4eff2cf2-342e-11e8-816f-10e0b2c5e3c9.png)

**Comment by ermeckle** [comment]
Do you get an error if you run:
```bash
tf.exe resolve -prompt E:\ROOTOD -recursive -preview
```

**Comment by souravprakashjena** [comment]
"**Execution of Tfvc command line failed unexpectedly** " . i am getting this error with VSCOde

**Comment by dheerajawale** [comment]
> 
> 
> "**Execution of Tfvc command line failed unexpectedly** " . i am getting this error with VSCode @jeffyoung

Did it work by any chance?

**Comment by abidalis** [comment]
> See #325. I have a fix coming soon, but in the meantime you can workaround this with these steps (also from that link):
> 
> 1. Open Developer Command Prompt for VS 2017
> 2. Navigate to the workspace root folder
> 3. Enter "tf workspace"
> 4. Login
> 
> That will cache your credentials then it will work.

Thanks !! It's working fine.

**Comment by dcp12345678** [comment]
@ermeckle , your workaround did not work for me.  When I did "tf workspace", I was never prompted to login.

**Comment by KenBrannigan** [comment]
It has been a year and this still seems to be a problem. When will this be fixed?

**Comment by shyambabu-kolipaka** [comment]
> See #325. I have a fix coming soon, but in the meantime you can workaround this with these steps (also from that link):
> 
> 1. Open Developer Command Prompt for VS 2017
> 2. Navigate to the workspace root folder
> 3. Enter "tf workspace"
> 4. Login
> 
> That will cache your credentials then it will work.

Thanks. It helps.

**Comment by devoneonline** [comment]
Thanks It Helps

**Comment by vladpach** [comment]
Does it fixed?
I still have this error
It appears you are using a Server workspace. Currently, TFVC support is limited to Local workspaces.
