### ISSUE TITLE
Unable to use the personal access token for VSTS online

### ISSUE THREAD

**Issue by suhasrs** [microsoft/azure-repos-vscode#391]
After configuring TF.exe for VS code, and after doing team-signin, when I try to doa  remtoe operation (sync/push/pull), it asks for username and password. I do not have Alternate credentials enabled, but it still asks. I tried both Manual method and the Automatic token assignment method. The only way I could solve this was setting an Alternate credentials with username and password and using that to Login. This issue is happening only on one machine. I tried in other machines, works fine there with same VSTS account.

I have VS 2015 Update 4 (community edition) installed on both the machines. 
VS code version is latest i.e. 1.22.1

How do I debug/solve this issue ?

**Comment by westerdaled** [comment]
Hi

I am in a similar position but with and without the company proxy .  I am using an ADFS account which might be causing issues.  Normally my client has MFA enabled and this is just adding to the problem synchronising with VSTS Online.  I think the best approach is replicate the sync function of the plugin using git CLI commands - assuming that isn't what is happening anyway behind the scenes .
