### ISSUE TITLE
Execution of the TFVC command line failed unexpectedly

### ISSUE THREAD

**Issue by aaron-bond** [microsoft/azure-repos-vscode#393]
**vsts-vscode version**: 1.1.33.0
**vscode version**: 1.22.2
**Visual Studio version**: 2017

I'm connecting to an on premise VS TFS  instance and I have the extension working to the point where I can view work items and the repository.
Unfortunately, on checkin I get the following message in the log:
```
tf checkin -noprompt ******** C:\myrepo\myfile -comment:#1
[Checkin] Execution of the TFVC command line failed unexpectedly.
```

I have a feeling this might be caused by our gated-checkin requirements. There's a prompt to build the solution before the checkin is confirmed. Is that supported?

**Comment by imoore** [comment]
I'm also connecting to an on premise VS TFS instance and I also have the extension working to the point where I can view work items and the repository.

I have the exact some problem when trying to check in my code I have added a work item to my code and a commit message as a policy of the repo.

**vsts-vscode version:** v1.133.0
**vscode version:** v1.23.0
**Visual Studio:** 2017

**Comment by jasterba** [comment]
Same here.
```
Using TFVC command line: /home/user/Documents/Code/Utils/TEE-CLC-14.114.0/tf (14.114.0.201703081734)
tf status -noprompt -collection:http://tfs-app/tfs/internal_projects ******** -format:xml -recursive 
```
(team) Execution of the TFVC command line failed unexpectedly.

Latest VSCODE and extension
TFS 2017

**Comment by m-malik15** [comment]
I'm having exactly the same issue and unable to check in the code ( & getting the error "(team) Execution of the TFVC command line failed unexpectedly."). I can view the repository include, exclude files options etc.

**Comment by sjeatdsi** [comment]
I'm getting the "Execution of the tfvc command line failed unexpectedly." message as well now. This is a new issue for me as everything was working a few days ago.

**Comment by clem4net** [comment]
Hello,
I have the same problem but I found a solution !
In Visual Studio, I set my workspace to "Public".
The problem was a create the workspace with an user, but try to access it with an other user from VS Code.
Bye

**Comment by sjeatdsi** [comment]
Unfortunately, that didn't work for me...

**Comment by imoore** [comment]
I'm still getting this issue even tho my VSC has been updated to the latest version

**vsts-vscode version:** v1.133.0
**vscode version:** v1.24.0
**Visual Studio:** 2017

**Comment by jasterba** [comment]
Found out that when there are folders/files with $, the tf command stops execution. There is a thing called tfignore (like gitignore) which can help with node_modules or any other folders/files that can contain such characters. Not sure why others hadn't needed it before I applied the rules, but those might be the quirks of VS 2017 and .sln files projects whatsoever that others use.

**Comment by joshuawootonn** [comment]
@imoore I am late to the discussion, but are you still getting the error? 

### vsts-vscode version: 1.136.0
### Vscode: 1.26.0
### VS: 2017

**Comment by famkafv** [comment]
We encounter the same error when checking into tfs. This problem started a couple a days ago, before it worked wel. Doing a refresh, to check the changes with tfs works fine. So it seems that there is no problem with the connection towards tfs.

Error message:  [Checkin] Execution of the TFVC command line failed unexpectedly, besides this there is no error info. **How can we see more log info from tfvc?**

Other info:
Settings: "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\TF.exe",

**vsts-vscode version: 1.136.1
Vscode: 1.26.0
VS: 2017**

**Comment by yolofam** [comment]
We encounter the same error when checking into tfs. This problem started a couple a days ago, before it worked wel. Doing a refresh, to check the changes with tfs works fine. So it seems that there is no problem with the connection towards tfs.

Error message: [Checkin] Execution of the TFVC command line failed unexpectedly, besides this there is no error info. How can we see more log info from tfvc?

Other info:
Settings: "tfvc.location": "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe",

vsts-vscode version: 1.136.1
Vscode: 1.26.0
VS: 2017

**Comment by Anu13sree** [comment]
Error message: [Checkin] Execution of the TFVC command line failed unexpectedly
Other info:
 Settings: "tfvc.location": "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe",


Any suggestion please

**Comment by yolofam** [comment]
I found a source (i believe there are aswell others) of this issue.
When trying to checkin files that were already deleted, this problem occured. 
When deleting files with vs code, it still keeps a reference in the excluded changes, when I included the excluded changes (aka the delete file) the error occured, which makes sense.
So in order to resolve this I deleted the excluded changes, that solved it.

**Comment by miguellira** [comment]
I encountered the same issue. For me it was due to renaming and/or moving files around. Especially if you do so outside Visual Studio Code. Simply undo the change and you'll be able to commit.

**NOTE:** Depending on the number of changes it may not be clear which are failing, you can just double click each change and if Visual Studio complains you found the winner 😄
