### ISSUE TITLE
Can't signin to on-prem TFS 2016 with smartcard

### ISSUE THREAD

**Issue by Xeelee33** [microsoft/azure-repos-vscode#400]
I dug through the other issues, and it looks like this hasn't been addressed yet.

Our environment uses smart cards (PIV) to authenticate user accounts against AD, which means we don't have a password to go along with our domain account. Visual Studio 2015, IE, and Chrome log us into TFS automatically by passing the credentials through, but the extension requests a password, and then obviously fails when it doesn't receive one.

Microsoft Visual Studio Team Foundation Server Version 16.122.27102.1
Visual Studio Code Version 1.23.1
Extension Version 1.133.0

**Comment by DGDC** [comment]
I have the same issue with TFS 2018. Is it possible to use security tokens for access to local on-premises versions of Team Foundation Server?
