### ISSUE TITLE
Error connecting to TFS after updating VSCode 1.23.1.0

### ISSUE THREAD

**Issue by m-malik15** [microsoft/azure-repos-vscode#408]
I'm getting the following error after updating the VSCode. When I try to team sign in by automatically authenticate option

"An error occurred requesting a personal access token for https://xxx.visualstudio.com. (Cannot read property 'x-vss-resourcetenant' of undefined)"

I've also tried manually entering PAT token and get the "connect ECONNREFUSED" error in the status bar with Team exclamation mark

[team-extension.log](https://github.com/Microsoft/vsts-vscode/files/2062109/team-extension.log)

**Comment by whoisj** [comment]
Eek! Sounds like it might be related to #406 by @chrisrpatterson. Hopefully not, but just in case @chrisrpatterson  can you take a quick look? Thanks!

**Comment by m-malik15** [comment]
I've found a similar  issue #375. Any ideas?

**Comment by BartNetJS** [comment]
Issue still exits on 1.26.1
