### ISSUE TITLE
Cannot associate Work Items in VS Code 1.24

### ISSUE THREAD

**Issue by Steveja74** [microsoft/azure-repos-vscode#411]
Hi. I have VSTS version 1.136.0 installed with VSCode 1.24.0. When I select Associated with Work Item, nothing appears in the commit message...I know this was fixed for previous versions...do I need to downgrade?

**Comment by alexw10** [comment]
I am also seeing this problem.
Any update on this?

**Comment by pmoison** [comment]
Same issue. 
Very important for code change tracking...

**Comment by wilsonparson** [comment]
Same for me. When I execute the 'Associate Work Items' command, all my work items show up, but when I select one of them, nothing happens. For what it's worth, when I click a work item the Developer Tools console (logging set to 'debug' in preferences) shows a deprecation warning, which I think is probably related to the issue.

![Screen Shot 2019-03-19 at 12 51 12 PM](https://user-images.githubusercontent.com/23664709/54633573-0f843700-4a46-11e9-8b93-cefe5b49aecf.png)

VS Code: 1.32.3
Azure Repos: 1.149.2

**Comment by wilsonparson** [comment]
Update: The deprecated method is not the issue, for me at least. See my comment in #433.

**Comment by waterkamp** [comment]
It's still a problem in VSCode 1.38.1

I'm not able to assign a workitem. Nothing happens when I select the workitem in the workitem-dropdown.

This is an important functionality. I have to switch to Visual Studio always, if I want to checkin code with assigned workitems.

Thanks for for any feedback.

Cheers,
Oliver

**Comment by alexgman** [comment]
Has this been fixed yet?

**Comment by boris01** [comment]
Any news on this issue?
This is a very important functionality.

**Comment by alexgman** [comment]
just type the item # in the comment and it will be associated

**Comment by domjg85** [comment]
I would also love to hear any progress or workaround on this? We're using tfs API and workitems are not being associated to check-ins, very frustrating
