### ISSUE TITLE
"A new personal access token was added to your account" on every launch

### ISSUE THREAD

**Issue by jacobludriks** [microsoft/azure-repos-vscode#414]
Issue Type: <b>Bug</b>

Upon opening VSCode, it creates a new personal access token every time and I get an email.

Git: https://<tenant>.visualstudio.com/ on <computername>
	Scopes: vso.code_write vso.packaging
	Expiration: 6/27/2019

Extension version: 1.136.0
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.12GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by whoisj** [comment]
This is because a new personal access token is being generated constantly by something. 

@jacobludriks are you using TFVC or Git? If Git, then please [report using the GCM issue tracker](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues). If TFVC, can you check your 
__Manage Windows Credentials__ (you can find by opening the Start Menu and searching for it)?
/CC @jeschu1

**Comment by jacobludriks** [comment]
I'm using Git. What shall I log to GCM?

**Comment by whoisj** [comment]
@jacobludriks the fact that you're getting repeated tokens likely has nothing to do with vso-vscode plugin, as this plug-in has everything to do with TFVC and nothing to do with Git.

VScode relies on your installed (aka system) Git package, and the GCM co-ships with Git for Windows, and it's responsible for creating personal access tokens for Git to use as HTTPS credentials.

The most likely system at fault here is VSCode (as it would be making the continuous requests for authentication), but the question here is why is a new PAT being generated each time? I can help you more on the correct issue tracker. Thanks.
