### ISSUE TITLE
The size of the request headers is too long.

### ISSUE THREAD

**Issue by jdshkolnik** [microsoft/azure-repos-vscode#415]
I'm unable to authenticate to VSTS using current or new method. If I provide the token directly, nothing happens. If I do the new method, I enter code into browser and, upon return, the extension errors out with...

`(team) An error occurred requesting a personal access token for https://blah-blah.visualstudio.com. (400 - "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Request Too Long</h2>\r\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\r\n</BODY></HTML>\r\n")`

I tried signing out and in, disabling/enabling, uninstalling/installing, no luck.

**Comment by whoisj** [comment]
@jdshkolnik could you please use a tool like [Fiddler](https://www.telerik.com/download/fiddler) to capture the interaction? Perhaps your headers __are__ too big, and once we have the headers recorded, we can look at them and how/why this is happening.

[Decrypting HTTPS traffice](https://www.fiddlerbook.com/fiddler/help/httpsdecryption.asp)

**Comment by asherjvitek** [comment]
I am having the same issue and was able to debug into it and see what is going on.

When I authenticate my Access Token is 11262 characters long. The code in deviceflow.js then calls getIdentityServiceUrl and this tries to put the accessToken into the headers as base64. After the base64 encoding the token is 15030 characters.

getIdentityServiceUrl is the function call that then fails. Oddly, we are able to execute getAuthenticatedUserId without error using the same accessToken.

Azure Repos Code:
File: \azure-repos-vscode-master\src\team-extension.ts
Line: const accessToken: string = await dfa.WaitForPersonalAccessToken();

[VSTS Device Flow Auth](https://github.com/microsoft/vsts-device-flow-auth):
File: \vsts-device-flow-auth\src\deviceflow.js
Function: getIdentityServiceUrl

It looks like what is happening is that we are using our Azure Repo url and then making a request to /_apis/ServiceDefinitions/LocationService2/951917AC-A960-4999-8464-E3F0AA25B381?api-version=1.0 and this is the api endpoint that throws the error.

I am happy to provide more details if need.
