### ISSUE TITLE
Plugin very slow

### ISSUE THREAD

**Issue by Lintzman** [microsoft/azure-repos-vscode#416]
Just started using this plugin and find it painfully slow to do anything. Connected to a local repository, for example:

It takes around 45 seconds to move 1 file from the Exclude Changes section to the Include Changes section (and visa versa)
It takes around 1 min 30 seconds to check in 1 file

Doing the same actions in Visual Studio are done in a matter of seconds so why the delay in VS Code?

Are there any settings that can speed this  plugin up so it is usable?

**Comment by trousyt** [comment]
I'm having the same issue with general slowness. In TFVC Output I can see the TF.exe command being issued and it takes a long time to return.

**Comment by BernieWhite** [comment]
Sounds related to #286
