### ISSUE TITLE
Error on "Team:signin" after pushing local git repo to VSTS

### ISSUE THREAD

**Issue by klinge** [microsoft/azure-repos-vscode#428]
I just tried installing and start using the VS Code VSTS plugin. I have a local git repo. I used the command line instructions to created a new project on VSTS and then followed the instructions to set a new remote in the local repo and then pushed everything to the new VSTS remote. like below. 

```
  git remote add origin https://xxxx.visualstudio.com/xxx/_git/ProjectName
  git push -u origin --all
```

This worked like it was supposed to and I can push and pull code from the VSTS git repo using VS Code. But when i try to use the "Team: signin" function I get an error message: 

> (team) No Team Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder that contains a repository.

After enabling the logging I see this in the error log: 

> 2018-09-06T12:52:25.953Z - info:   [08560] *** FOLDER: c:\dev\xxx\xxx ***
> 2018-09-06T12:52:25.953Z - info:   [08560] VSTSVSCode/1.136.0 (VSCode 1.26.1; Windows_NT 6.1.7601; Node 8.9.3)
> 2018-09-06T12:52:25.953Z - debug:  [08560] Looking for an External Context at c:\dev\xxx\xxx
> 2018-09-06T12:52:25.953Z - debug:  [08560] No External Context at c:\dev\xxx\xxx
> 2018-09-06T12:52:25.953Z - debug:  [08560] Looking for TFVC repository at c:\dev\xxx\xxx
> 2018-09-06T12:52:25.953Z - debug:  [08560] TFVC Creating Tfvc object with localPath='undefined'
> 2018-09-06T12:52:25.953Z - debug:  [08560] Using TFS proxy: 
> 2018-09-06T12:52:25.953Z - debug:  [08560] TFVC Retrieved from settings; localPath='C:/xxx/TEE-CLC-14.114.0/tf.cmd'
> 2018-09-06T12:52:25.953Z - debug:  [08560] TFVC Repository created with repositoryRootFolder='c:\dev\xxx\xxx'
> 2018-09-06T12:52:25.969Z - debug:  [08560] TFVC Repository.CheckVersion
> 2018-09-06T12:52:25.969Z - debug:  [08560] TFVC: tf add -noprompt -?
> 2018-09-06T12:52:25.969Z - debug:  [08560] TFVC: spawned new process (duration: 0ms)
> 2018-09-06T12:52:25.985Z - debug:  [08560] TFVC: spawned new process (duration: 16ms)
> 2018-09-06T12:52:28.563Z - debug:  [08560] TFVC: add exit code: 0 (duration: 2594ms)
> 2018-09-06T12:52:28.563Z - debug:  [08560] TFVC Minimum required version: 14.0.4
> 2018-09-06T12:52:28.563Z - debug:  [08560] TFVC (TF.exe, TF.cmd) version: 14.114.0.201703081734
> 2018-09-06T12:52:28.563Z - debug:  [08560] TFVC Repository.FindWorkspace with localPath='c:\dev\xxx\xxx'
> 2018-09-06T12:52:28.563Z - debug:  [08560] TFVC: tf workfold -noprompt c:\dev\xxx\xxx
> 2018-09-06T12:52:28.563Z - debug:  [08560] TFVC: spawned new process (duration: 0ms)
> 2018-09-06T12:52:30.709Z - debug:  [08560] TFVC: workfold exit code: 100 (duration: 2146ms)
> 2018-09-06T12:52:30.709Z - debug:  [08560] TFVC errors (via stderr): An argument error occurred: The workspace could not be determined from any argument paths or the current working directory.
> 
> 2018-09-06T12:52:30.709Z - debug:  [08560] TFVC errors (via stdout): Team Explorer Everywhere Command Line Client (version 14.114.0.201703081734)
> 
>  workfold command:
> 
>   Creates, modifies, or displays information about the mappings between your
>   workspace folders and the source control server folders to which they
>   correspond.
> 
>  Valid option sets:
> 
>   workfold /cloak [/collection:<url>] [/workspace:<value>]
>            <serverFolder>|<localFolder>
>   workfold /decloak [/collection:<url>] [/workspace:<value>]
>            <serverFolder>|<localFolder>
>   workfold /unmap [/collection:<url>] [/workspace:<value>]
>            <serverFolder>|<localFolder>
>   workfold [/collection:<url>] [/workspace:<value>] <serverFolder>
>   workfold [/map] [/collection:<url>] [/workspace:<value>] <serverFolder>
>            <localFolder>
>   workfold [/workspace:<value>]
>   workfold <localFolder>
> 
> 
> 2018-09-06T12:52:30.709Z - error:  [08560] Could not find a workspace with mappings (e.g., not a TFVC repository, wrong version of TF is being used).

I also created an empty project on VSTS and imported that into VS Code. For that project everything is working ok. 

Any suggestions on what is wrong  and how to fix it would be appreciated!

**Comment by klinge** [comment]
I still do not know what went wrong earlier. Just want to report that I found a workaround that solved the issus of the Team plugin in VS Code not recognizing my local folder as a repository by: 

1. deleting the local repository folder and
2. cloning the repo from VSTS 

After doing this the local repo is recognized by the team plugin and everything is working fine!

**Comment by hammady** [comment]
I am having the same issue, only repos cloned from DevOps using the "Clone in VS Code" work, but those manually cloned don't.

**Comment by hammady** [comment]
btw, I also discovered that it does not work with repos cloned via ssh. Only https. In the cloned repo in my previous comment, if I change the repo remote url to ssh the extension stops detecting it. When I set it back to the https url it works again. This is inconvenient to me because I always use ssh so that I don't type the credential every single time i push or pull.

**Comment by hammady** [comment]
Turned out that it is all about putting the correct clone URL. The SSH URL has changed multiple times. Check #333 and #374.
