### ISSUE TITLE
Associate workitem with TFVC repository doesn't work

### ISSUE THREAD

**Issue by pmatsconsulting** [microsoft/azure-repos-vscode#433]
Associate workitem with TFVC repository doesn't work

**Comment by dfaroi** [comment]
Hello,

Could you please give us a status update regarding this issue ?

Thanks
Kind regards.
David

**Comment by dfaroi** [comment]
Linked issue : #411

**Comment by ML273** [comment]
Same issue. I can see the work item in the drop down from command palette, but upon clicking, the drop down disappears/nothing else happens. After checking in, the changeset is not associated to the work item.

VSC version: 1.30.2
Azure Repos v1.144.1

**Comment by choudharydhaka** [comment]
Same issue, with VSC version 1.31.0.

![image](https://user-images.githubusercontent.com/42489476/52449204-4b042980-2b9b-11e9-88a8-5055abc6b58a.png)

**Comment by wilsonparson** [comment]
I've been having the same issue. I looked into it a little more deeply today, and I discovered that the method `[TeamExtension.withSourceControlInputBox](https://github.com/Microsoft/azure-repos-vscode/blob/2908ec899d1ebc2a9a4e26b105307f7755c8ec95/src/team-extension.ts#L506)`, which is called by `[TeamExtension.appendToCheckinMessage](https://github.com/Microsoft/azure-repos-vscode/blob/2908ec899d1ebc2a9a4e26b105307f7755c8ec95/src/team-extension.ts#L374)`, looks for open git repositories, not TFVC repositories. So with a TFVC repo open, I get an empty array back from `[getRepositories](https://github.com/Microsoft/azure-repos-vscode/blob/2908ec899d1ebc2a9a4e26b105307f7755c8ec95/src/team-extension.ts#L506)`, which exits the call stack.

I guess this means that currently there is no implementation for associating work items with TFVC repos?

**Comment by miftaurrahaman** [comment]
Hi,
When I can expect to be solve this issue ? Any expert comment on this please.
Thanks,
Miftaur

**Comment by waterkamp** [comment]
It's still a problem in VSCode 1.38.1

I'm not able to assign a workitem. Nothing happens when I select the workitem in the workitem-dropdown.

This is an important functionality. I have to switch to Visual Studio always, if I want to checkin code with assigned workitems.

Thanks for for any feedback.

Cheers,
Oliver

**Comment by wilsonparson** [comment]
For what it’s worth, the workaround I’ve been using for the past 6 months has been to reference the work item ID in the commit message (e.g., fixed the thing #12345), and tf just knows to associate to the work item with that ID. I actually like it this way more, with the work item explicitly referenced in the message. Works for multiple work items as well.

**Comment by serhaton** [comment]
Any update please ? 
This is still an issue with version 1.42.1 
#12345 does not work either from the comment box. 

Thanks

**Comment by managerger** [comment]
Guys, any update on this. It is still an issue for 1.47.3

**Comment by domjg85** [comment]
I would also love to hear any progress or workaround in this? We're using tfs API and workitems are not being associated to check-ins, very frustrating.
