### ISSUE TITLE
Unable to find the TF executable.

### ISSUE THREAD

**Issue by olisterr** [microsoft/azure-repos-vscode#434]
Hi,
When creating a connection between VS Code and TF in the User Settings I've already added the configuration as follows

{
    "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\tf.exe"
}

![image](https://user-images.githubusercontent.com/35020704/45875876-91a4e300-bdb6-11e8-9da0-a04314dfa243.png)

Kindly advise.

**Comment by HerrB92** [comment]
Hi olisterr,

if you are using some of the later VSCode versions check the setting using the Settings editor (having a "user friendly" UI). Here, the path should be visible exactly as it is in Windows Explorer (with spaces, single slashed) - internally, the editor adds double slashes.

It may still happen that you get the error message - I guess the check is somehow wrong and subsequent changes does not seem to refresh the notification, either. It may still work.

Regards,
HerrB92

**Comment by lisawells87** [comment]
I have been struggling with this as well.  HerrB92's advice to do this in the Settings GUI for the extension finally fixed my problem.  This is what worked for me, on MacOS Mojave, VS Code 1.39.2, using TEE-CLC as installed by Homebrew:

`⁨usr⁩/local⁩/⁨Cellar⁩/tee-clc⁩/14.134.0⁩/⁨bin⁩/tf`

Hope that helps someone, good luck!

**Comment by JohnLBevan** [comment]
I had a similar issue.  Should it help others, my issue was after upgrading from VS2017 to VS2019 the related path changed, but I'd not updated my settings.

- Run VS Code
- Click File > Preferences > Settings 
- Search for setting "tfvc"
- The Azure Repos extension shows as one of the results.  This has the setting `Tfvc:Location` defined
- Check and correct this value.  An easy way to check is to copy the path into the terminal console, and run `Get-Item 'paste-path-here'`.  If an item is found then the above is not your issue.  If it's not, open Windows Explorer and work your way through the path to find what's missing (in my case I found `c:\Program Files (x86)\Microsoft Visual Studio`, but the subfolder 2017 wan't there / 2019 was.

Note also that there are both User and Workspace settings.  Check both locations (you'll see different tabs in your search results after the 3rd step above).
