### ISSUE TITLE
VSTS is now Azure Repos : Finishing touches

### ISSUE THREAD

**Issue by cslecours** [Microsoft/azure-repos-vscode#437]
Following VSTS product name change : 

1. This extension is still called Visual Studio Team Services.
2. Getting Started documentation is confusing as it tells to search for team and select Azure Repos. (Bulk renaming side effect!)

> The Visual Studio Code Extension
To install the extension with the latest version of Visual Studio Code (version 1.11.1 is the latest as of this writing), bring up the Visual Studio Code Command Palette (F1), type install and choose Extensions: Install Extensions. In the Search Extensions in Marketplace text box, type **team**. Find the **Azure Repos** extension published by Microsoft and click the Install button. Restart Visual Studio Code.

Source : https://github.com/Microsoft/azure-repos-vscode/blob/master/TFVC_README.md#the-visual-studio-code-extension

**Comment by jrbriggs** [comment]
Thanks for raising this. We have republished the extension as "Azure Repos"
