### ISSUE TITLE
Azure Repo Pull Request Management

### ISSUE THREAD

**Issue by ErikElkins** [microsoft/azure-repos-vscode#438]
The GitHub Pull Requests vs code plugin was announced a while back (https://github.com/Microsoft/vscode-pull-request-github). The work done for that extension made it easier to implement a similar feature in other plugins. 

I'm wondering if we should include that feature in this plugin, or create a new plugin for that feature. I'd be happy to help implement this feature over the next month.

**Comment by kaylangan** [comment]
We don't currently have this planned, but we're happy to accept contributions!

**Comment by tostca** [comment]
It would be really awesome to have this kind of support in the Azure Repos extension aswell

**Comment by Camo30** [comment]
Would be great to get that feature. Today its kind of inconvenient to work with pull requests in vs code

**Comment by thomstak** [comment]
I'm wondering why Microsoft only focuses on the development of the above pull request plugin, which only works with GitHub (like the name of it says). Developer teams who are using Azure DevOps are left out of this enhancements

**Comment by stoianchoo** [comment]
I would like this functionality as well.
Wondering why in editor reviews are not planned by the team.

**Comment by mshinnie** [comment]
I agree this feature should definitely be implemented.
