### ISSUE TITLE
Incorrect detection of workspace

### ISSUE THREAD

**Issue by jrichview** [microsoft/azure-repos-vscode#449]
I've installed the extension and provided credentials which have been accepted. However the extension detects my workspace as being a server workspace when it is, in fact, a local workspace. I can see and edit it within VS2017.

**Comment by BrianThorChristensen** [comment]
I agree. This is very annoying. I had the extension working fine until today. Now suddenly my local workspace is detected as a server workspace.

**Comment by KenBrannigan** [comment]
I have the same issue. Do we have any resolution for this yet?

**Comment by jrichview** [comment]
Not that I have seen.

**Comment by BrianThorChristensen** [comment]
It seems that you can temporarily fix this by opening the workspace window.
Press ctrl+comma.
Go to azure repos.
Copy the path to tf.exe.
Switch to the terminal pane (powershell).
Type: & "<paste your path>" 'vc' 'workspace'
Close the opened window.
Reload the vscode window.

Hope this helps you.
I do this on any workstation that shows this behaviour and it has always worked so far.

**Comment by jrichview** [comment]
I'll try this when I get a chance. What do you mean by "temporarily fix" ?

**Comment by BrianThorChristensen** [comment]
The problem shows up from time.
I don't know why. It seems quite random.
I just go through those steps, and it'll work again until next time.

**Comment by KenBrannigan** [comment]
Thanks, @BrianThorChristensen that worked for me. It made me re-authenticate.
