### ISSUE TITLE
Unable to configure Azure DevOps PAT

### ISSUE THREAD

**Issue by spncrgr** [Microsoft/azure-repos-vscode#452]
I've just installed Visual Studio Code and the Azure Repos extension. When I get the notification to configure the extension, I click on the 'Set Up TFVC Support' button, but nothing happens.

I've also tried to enter my PAT manually, but I can't seem to find a way to do that.

Please let me know if there's any additional information I can provide to help figure this out.

**Comment by HerrB92** [comment]
Hi spncrgr,

have you followed the steps as described in the readme.md of this project (https://github.com/Microsoft/azure-repos-vscode)?

After installation of the extension you at least to configure some settings (see readme.md) within the VSCode settings (File > Preferences > Settings, if you are using some of the later VSCode versions).

Regards,
HerrB92

**Comment by spncrgr** [comment]
Sorry about that. What was messing me up was not having a folder, containing a git repo, open in VS Code when attempting to configure. I do remember reading that before, in the readme, but it just didn't register until now SMH
