### ISSUE TITLE
Feature Request: Start pipelines from VS Code

### ISSUE THREAD

**Issue by chadsowald** [Microsoft/azure-repos-vscode#453]
It would be great if I could get a list of my pipelines and could start 1 directly from VS code instead of having to go to the DevOps site.

**Comment by vtbassmatt** [comment]
Hi @chadsowald - we have a separate extension for working with Pipelines. Is [this feature](https://github.com/Microsoft/azure-pipelines-vscode/issues/104) akin to what you're looking for? If not, please feel free to [file a new one](https://github.com/Microsoft/azure-pipelines-vscode/issues/) over there. Thanks!
