### ISSUE TITLE
Does this support Azure Devops and Git?

### ISSUE THREAD

**Issue by michaeltarleton** [microsoft/azure-repos-vscode#454]
If this does work with Azure Devops with Git repos, can someone point me in the right direction in getting it setup?

Thanks in advance!

**Comment by HerrB92** [comment]
Hi michaeltarleton,

have you followed the steps as described in the readme.md of this project (https://github.com/Microsoft/azure-repos-vscode)?

After installation of the extension you at least to configure some settings (see readme.md) within the VSCode settings (File > Preferences > Settings, if you are using some of the later VSCode versions).
