### ISSUE TITLE
TFS Getting Started Step-By-Step Guide

### ISSUE THREAD

**Issue by HerrB92** [microsoft/azure-repos-vscode#455]
Hi everyone,

maybe because I am rather new in VSCode + TFS + current web development I found it rather difficult to connect VSCode with TFS/TFVC and to get started. It would be nice, if the readme.md could get a step-by-step chapter only for TFS/TFVC integration.

In the readme.md TFS/TFVC configuration and usage is rather "sprinkled in" and some information about some "obvious" tasks I was not able to find, yet (which may be there, but ... or I am doing something wrong).

Some issues I had/have:
- While I found the information & explanation about workspaces in VSCode, I did not find an information, which folder structure may be the best, if you are working with TFS/TFVC (and you want to keep several "projects" within the same "solution"). Should I use a workspace? Or just several folders? But how can I configure the tf.exe path only once? I ended up with
  - Workspace folder (contains the code-workspace file, also with the plugin configuration)
    - Project A folder
    - Project B folder
    - ...
- While several commands are described for "Git only", I missed the equivalents for TFS/TFVC. Maybe I have just overseen them, but for example I have not found the command to clone/check out/"Get the Latest Version" and ended up using Visual Studio Professional to get the content on the TFS/TFVC server (all explanations/videos start with "I have a TFS enabled folder" which contains already files). And there does not seem to be a "clone/..." command in the UI, either.
- The readme.md and a lot of pages in the web explain to search for "team" (sometimes also "Team Services") within the extensions list to find and install the required plugin. Unfortunately, the plugin is now named "Azure Repos". With "team" you may find it by scrolling down two pages, but you still do not get the idea, that this extension (showing only an orange icon) also provides TFS/TFVC integration. And you know, even the Team Foundation Server 2018 is still named TFS, not TFVC... ;-)

I would suggest a TFS/TVFC get started chapter as something like this (corrections/additions appreciated):
>>>
Team Foundation Server (TFS) or Team Foundation Version Control (TFVC) integration for Visual Studio Code on Windows:

1.  You currently have to create a TFS/TFVC enabled workspace **outside** VSCode.
1. To create a TFS/TFVC workspace:
   1. Install Visual Studio (Professional, Enterprise or for free the Community edition, available here: https://visualstudio.microsoft.com/en/downloads/). You may use alternative IDEs (Eclipse/JetBrains IDEs, e.g. Android Studio, IntelliJ) to create the workspace, but you need the Team Explorer integration (tf.exe) of Visual Studio later, to connect with TFS/TFVC.
   1. Create a new folder using Windows Explorer which should become your workspace
   1. If you are using Visual Studio, configure the folder as TFS/TVFC enabled workspace as described here: https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/share-your-code-in-tfvc-vs?view=vsts. Please check the Eclipse or JetBrains documentation, on how to create a TFS enabled workspace, if you are using these.
1. Optional: Convert the workspace folder to a VSCode multi-project workspace by adding a file named "CodeWorkspace.code-workspace" (without quotes) within the workspace folder with the following content:
   ```
   {
   	"folders": [
   	]
   }
   ```
1. Search for the tf.exe provided by the Visual Studio Team Explorer integration and remember/copy the path. With VS 2017 it may be located here: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
1. If you have created a code-workspace file before, right-click on the file and choose "Open with Code". Otherwise right-click on the workspace folder and chosse "Open with Code".
1. Open Extensions (File > Preferences > Extensions)
1. Search for Azure Repos (previous name: Visual Studio Team Services, just for reference) and install it
1. Open Settings (File > Settings). The following steps describe the configuration with the new "user friendly" Settings editor.
1. If you have created a code-workspace file before, click on Workspace Settings (below the "Search" bar). Otherwise stay were you are.
1. Search for "tfvc" and click on "Azure ext..."
1. Look for the entry "Tfvc:Location" and there, specify the full path (including the file name) to tf.exe, e.g. C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\tf.exe. As we are using the "user friendly" Settings editor you can use the path "as-is" with spaces and single slashes - the editor does the rest. You may get an error that tf.exe was not found - it seems to happen as well with a correct path (still, check again).
1. Close Settings
1. You should now have a blue bar at the bottom showing the term "Teams" with some icon. Click on it and provide user name & password to log into the TFS/TVFC server. If server versions before 2015 SP2 are used, provide an access token (shown here: https://www.youtube.com/watch?v=6IzJ2UPGmoQ)
1. If you were able to log in, the name of the TFS/TVFC project website is shown in the blue bar (instead of "Teams").
1. If you have created a code-workspace file before, you may now like to add (existing) folders to your workspace (File > Add Folder to Workspace).

Change to Source Control (third icon on the left or View > SCM) and click on the Refresh icon to identify changes between your local files and the TFS/TFVC repository.

If you first want to clone/check out existing content of the TFS/TFVC repository, then start Visual Studio (not Code) or your preferred IDE and clone/checkout your files and folders (in Visual Studio Source Control Explorer, right-click, "Get Latest Version").

While you can submit/update files and folders within the SCM in VSCode, it seems you cannot clone/checkout/get the latest version by a menu item in the Azure Repos plugin. As described, use the "real" Visual Studio or your preferred IDE to transfer existing content from TFS/TFVC server.
<<<

Regards,
HerrB92

**Comment by rfalanga** [comment]
I just discovered this post you made @HerrB92. Thank you! I intend to go through it slowly! (Gotta pack up and go now.) I've been through the documentation several times, unsuccessfully able to get VS Code to work with TFVC. I always get stuck at (this spot)[https://github.com/Microsoft/azure-repos-vscode/blob/master/TFVC_README.md#open-a-local-tfvc-repository-folder]. Code **never** prompts me to log into my Azure DevOps TFVC repo. Hopefully your tutorial will make it plainer.
