### ISSUE TITLE
how check out and edit file

### ISSUE THREAD

**Issue by ehsanarian** [microsoft/azure-repos-vscode#457]
Thanks for this great extension.
how check out file when open it and lock file for another users

**Comment by abhidotnet** [comment]
**Perhaps I am doing something wrong**, but I am using the tf command line utility outside of visual studio to checkout and checkin files. I couldn't use this extension to work in the way I wanted.

Each time I tried to use the graphical menu to check in files, I get the following message:

`Execution of the TFVC command line failed unexpectedly.`
