### ISSUE TITLE
TFS Authorization broke

### ISSUE THREAD

**Issue by SteveScott** [microsoft/azure-repos-vscode#479]
My team can no longer connect to TFS via Azure Repos. We had it working yesterday, but today we cannot log in to TFS via VSCode. We get the message "Unauthorized. Check your authentication credentials and try again". We can, however log into VS2017 and push our code that way, so our TFS server is working. I know the password is correct because it is the same as our workstation password, and the user name is auto-populated. Any insight? Does this have to do with an update to VSCode?

**Comment by RCKSTR1** [comment]
Happening to me too. Just after the January update :(

**Comment by dragoljub** [comment]
Same here. 🆘

**Comment by dragoljub** [comment]
I downgraded VS Code to 1.30.0 and was able to log into TFS.

https://github.com/Microsoft/azure-repos-vscode/issues/476#issuecomment-461631659

**Comment by SteveScott** [comment]
I see, it seems I posted a duplicate bug.

**Comment by clem4net** [comment]
+1
It's very problematic

**Comment by jRichardeau** [comment]
Same issue, I have to downgrade to VS Code 1.30

**Comment by dragoljub** [comment]
Has anyone on the Microsoft team seen this and responded yet? Is it know and being worked?

**Comment by ewaschenko** [comment]
I have the same error as well.  In VS Code in the bottom left it has Team with an exclamation mark, but if I try to pull or push it still works fine, so for me it's just the UI is incorrect, behind the scenes the extension is working.

**Comment by ewaschenko** [comment]
File > Preferences > Settings > User Settings > Application > Proxy Support On / Off

Credit to @Larhei

**Comment by benshabatnoam** [comment]
@ewaschenko you ment credit to @dragoljub

**Comment by ewaschenko** [comment]
@benshabatnoam Fix was actually found here in this issue 

[https://github.com/Microsoft/azure-repos-vscode/issues/485](https://github.com/Microsoft/azure-repos-vscode/issues/485)

**Comment by benshabatnoam** [comment]
You're right, 10x

**Comment by Larhei** [comment]
@ewaschenko credits to @chrmari found the answer https://github.com/Microsoft/vscode/issues/68531

**Comment by chrmarti** [comment]
This should be fixed in current insiders builds of VS Code with the Proxy Support setting set to 'override'. Let me know if you still see any issues with that. Download: https://code.visualstudio.com/insiders/

**Comment by cnavarro16** [comment]
Looks like this is still an issue. Was working fine up until yesterday when I did a password reset. Tried re-setting my password and kept getting the 'unauthorized' error. Had to remove the extension to be able to commit changes. 

![image](https://user-images.githubusercontent.com/15855433/87493633-8c521000-c690-11ea-8ef5-30710219f409.png)
