### ISSUE TITLE
Team signin: Unauthorized

### ISSUE THREAD

**Issue by Yeg-A** [microsoft/azure-repos-vscode#485]
https://github.com/Microsoft/vscode/issues/68442#issue-408888870

**Comment by Larhei** [comment]
Changing Settings>User Settings >Application > Proxy Support to On / Off instead of Override fixed the problem for me. Hope it helps

**Comment by wilhelmer** [comment]
Thanks, that worked for me too. Changed it to Off.

**Comment by dragoljub** [comment]
@wilhelmer  which version of VS Code are you on?

**Comment by Larhei** [comment]
@dragoljub I am on MAC VS Code 1.31.1

**Comment by wilhelmer** [comment]
Win 1.31.1

**Comment by dragoljub** [comment]
I switched proxy support for extensions off on latest VS Code stable 1.31.1 on Win 10 and TFS login is working for me now! Thanks! 👍

**Comment by voytas75** [comment]
1.31.1, change proxy support to OFF helped.

**Comment by ccerghed** [comment]
Same issue here - I've been struggling with this for 2 months now.
Adding this setting to my settings.json did the trick:    "http.proxySupport": "off"
