### ISSUE TITLE
(team) Unable to find the TF executable. Please ensure TF is installed and the path specified contains the filename.

### ISSUE THREAD

**Issue by sudheer9593** [microsoft/azure-repos-vscode#504]
Unable to connect to TFS in visual studio code when giving 

Tfvc: Location as 
''C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe''

**Comment by zatchgordon** [comment]
Have you tried removing the `.exe` from the path?

**Comment by JohnLBevan** [comment]
Please take a look at #434; this appears to be the same issue.
