### ISSUE TITLE
Create PR doesn't redirect to correct URL

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/azure-repos-vscode#506]
When I use the team: Create Pull Request action, it does a few redirects and then lands on the default pull request page w/o the source control branch populated.

The fix is using the PR formatted URL ADO expects, it looks like the code generating the URL is stale.

I had a PR pending when this was VSTS, but I guess it got lost in the rebrand :/

Edit: PR #431 

Let me know if you guys would be willing to accept a PR before I do the work again -- I use the function a LOT and it gets annoying after a year :)

**Comment by totkeks** [comment]
Came here to post exactly this bug. Still not working as of today. Also applies to the new ADO domain: `https://dev.azure.com/<organization>`, since the problem is in the path of the URL.
Can anyone approve the outstanding PR?
