### ISSUE TITLE
Browse your Pull Request

### ISSUE THREAD

**Issue by MarcvanLint** [microsoft/azure-repos-vscode#512]
Issue Type: <b>Bug</b>

The browse your pull request url needs additional ?_a=mine 
WIthout it no requests are shown.

Extension version: 1.149.2
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (4 x 3196)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|12.00GB (5.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>

**Comment by doggy8088** [comment]
Focus on the Location bar, hit Enter. Then you'll see things out.

**Comment by doggy8088** [comment]
I reported an issue here: https://github.com/microsoft/azure-repos-vscode/issues/535

**Comment by DavidDeSloovere** [comment]
> Focus on the Location bar, hit Enter. Then you'll see things out.

What a weird workaround. But works via keyboard, so good enough for me.

But really, this is annoying and rather an Azure DevOps issue than a VS Code extension issue.
