### ISSUE TITLE
"Associate workitem" adds commit message to incorrect repository when repository has a git submodule

### ISSUE THREAD

**Issue by sammeel** [microsoft/azure-repos-vscode#518]
**Situation**
Git repository that has a git submodule.

VsCode shows both repositories in de SCM tab.

![image](https://user-images.githubusercontent.com/1624852/57434659-bf527580-723b-11e9-9b10-09fa9ff93273.png)

The 1st repo is my main repo, the 2nd repo is my git submodule.

**Steps to reproduce**
Scenario 1
1. Open Command pallette
1. Choose "Team: Associate Work items"
1. Select the work item
1. Work item is attached to the git submodule repo

Scenario 2
1. open the SCM tab
1. Click the "..." button next to the first repo
1. Select "Associate Work Items"
![image](https://user-images.githubusercontent.com/1624852/57434843-2ec86500-723c-11e9-9aa1-265295314508.png)
1. Select the work item
1. Work item is attached to the git submodule repo

**Expected behavior**
In scenario 1, it is debatable which repo should get the work item commit message
In scenario 2, it should be attached to the selected repo

**System**
VsCode: 1.33.1
Azure Repos: 1.149.2

**Comment by novarider** [comment]
Hey i tried to resolve this issue. My code in the pull requests adds the associated work item message to all repositories in the workspace, not only one (the submodule).

greets

**Comment by sammeel** [comment]
With the last update of vscode (1.47.0) and the changes to the source control tab (https://code.visualstudio.com/updates/v1_47#_source-control), it is now impossible to associate a work item as we cannot open the other repositories to see the commit message.

I'd expect the commit message to be added to the current active repository, but the fix from Novarider should also work since the other repos don't show any commit message anymore when there are no changes
