### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by begunfx** [microsoft/azure-repos-vscode#520]
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.149.2`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/begun/ms-vsts.team-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by begunfx** [comment]
[ms-vsts.team-unresponsive.cpuprofile.txt](https://github.com/microsoft/azure-repos-vscode/files/3169275/ms-vsts.team-unresponsive.cpuprofile.txt)

**Comment by lgp1985** [comment]
Duplicate of #460
