### ISSUE TITLE
Unable to connect to TFS from VS Code V1.33.1

### ISSUE THREAD

**Issue by abhikumars** [microsoft/azure-repos-vscode#527]
Hi All,
i am a beginner in VS Code.
As per the given instructions in video i am unable to connect to TFS from VS Code V1.33.1.

Issues : 
1. Unable to search Visual Studio Team Services in **Extensions**
2. I have installed TFS plugin but unable to see Team symbol

Please help me on this ASAP.
Find the image for reference.
![tfs_vscode](https://user-images.githubusercontent.com/17405875/57848453-8e9fac80-77f6-11e9-8e26-c6ec0252ba63.png)

**Comment by abhikumars** [comment]
@jeffyoung Please help me out on this.

**Comment by DarthHumorous** [comment]
Install "Azure Repos" extension, not "Visual Studio Team Services".

These are the settings that worked for me, though I still get "No source control providers registered" under the "Source Control" viewer.

```
{
    "window.zoomLevel": 0,
    "telemetry.enableTelemetry": false,
    "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\tf.exe",
    "team.remoteUrl": "http://tfs.ourcompany.com:8080/tfs/ourcollection",
    "team.teamProject": "OurProject",
    "http.proxySupport": "off",
    "team.logging.level": "debug",
    "tfvc.restrictWorkspace": true,
    "team.showWelcomeMessage": false
}

```

**Comment by DarthHumorous** [comment]
BTW, I was able to get the Source Control viewer to display as expected when I removed the "team.teamProject" value.

See: https://github.com/microsoft/azure-repos-vscode/issues/531
