### ISSUE TITLE
Unable to use new https://dev.azure.com style url with Azure Repos in vscode

### ISSUE THREAD

**Issue by IanMoroney** [microsoft/azure-repos-vscode#528]
I noticed that when I issued a new pull request through the Azure Repos extension in VSCode, that the PR was opening with the old style url (https://customername.visualstudio.com) so I tried to force it instead to use the new style url with the workspace override settings:
team.remoteUrl
team.teamProject

When I set those settings and try a new pull request, i get an error from Azure Repos:

> (team) The open folder is not a Git repository. Please check the folder location and try again.

I don't see another way to set the extension to use the new https://dev.azure.com format (as that is the recommended URL to use now because of liveness and CORS and other sorts of things they have going on in Azure Devops)

**Comment by Nettsentrisk** [comment]
I'm getting a 404 Not Found error when I do team signin, the URL starts with dev.azure.com but I think the rest of it is wrong.
