### ISSUE TITLE
Azure Repos taskbar missing

### ISSUE THREAD

**Issue by jasonabergel** [microsoft/azure-repos-vscode#530]
Issue Type: <b>Bug</b>

I am not able to access my devops repo as the add-on is not working. It does not show up at the bottom left corner to login. I have tried disabling, re-enabling, reinstalled, but nothing.

Please help, thanks,

Jay

Extension version: 1.149.2
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.78GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>

**Comment by DarthHumorous** [comment]
I'm sure you would have figured this part out, but at one point I couldn't figure out why the taskbar wasn't showing up for me sometimes either.  Turns out I was not responding to the extension dialog in the bottom right of the screen.  Closing that dialog allowed the extension to fully load.  And you can turn off "Team: Show Welcome Message" so the dialog never holds up loading again.

**Comment by jasonabergel** [comment]
Thanks for the reply, however, mine has never shown and this is a new desktop so it was installed fresh. I do not see any dialogues to close or ane errors. I am truly stumped here and have no idea what to do to fix this.

**Comment by DarthHumorous** [comment]
FYI, this is the dialog I am referring to:

![image](https://user-images.githubusercontent.com/51243203/59303860-1b5a5080-8c65-11e9-8725-379d7448371e.png)

And these are the settings that worked for me:

```
{
    "window.zoomLevel": 0,
    "telemetry.enableTelemetry": false,
    "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\tf.exe",
    "team.remoteUrl": "http://tfs.ourcompany.com:8080/tfs/ourcollection",
    "team.teamProject": "OurProject",
    "http.proxySupport": "off",
    "team.logging.level": "debug",
    "tfvc.restrictWorkspace": true,
    "team.showWelcomeMessage": false
}

```

**Comment by DarthHumorous** [comment]
And FYI I'm using on-premise TFS.

**Comment by DarthHumorous** [comment]
BTW, I was able to get the Source Control viewer to display as expected when I removed the
"team.remoteUrl" and "team.teamProject" values.

**Comment by jasonabergel** [comment]
> And FYI I'm using on-premise TFS.

We are using Azure Devops and not on-premise. On premis doesn't appear to be an issue though.

![image](https://user-images.githubusercontent.com/29098468/59437513-b8c99780-8dbf-11e9-809b-c2e43635579f.png)

**Comment by jasonabergel** [comment]
Weird, I cleared all the setting for the Azure Repos extension, went back to Azure Devops to clone the repo and this time it worked. Thanks for your help @DarthHumorous
