### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by alphaCoder** [microsoft/azure-repos-vscode#54]
Apologies if this is not the right place to add the issue.

I downloaded vs code 1.5.3 and installed "Visual Studio Team Services Extension"
I supplied the team login credentials but I see the below image
![image](https://cloud.githubusercontent.com/assets/2112159/18933756/d9c05804-859b-11e6-8442-0c49eccafd3b.png)

When I hover on team it is showing  "Unable to get local issuer certifcate"
I added under UserSettings "http.proxyStrictSSL": false
but still getting the error.

Following the below issues
[https://github.com/Microsoft/vscode/issues/11774](url)
[https://github.com/Microsoft/vscode/issues/11702]()

I installed vs code insiders, still seeing the issue.

Thanks in advance for looking into the issue and appreciate any suggestions.

P.S. I am on vpn and connecting to on premise tfs server.

Thanks

**Comment by jeffyoung** [comment]
Hi @alphaCoder.

This is the proper place to file issues with the Team Services extension.  So you're good.

The extension doesn't use VS Code's http stack to communicate with TFS but instead uses the [vsts-node-api](https://github.com/Microsoft/vsts-node-api).  I'm not sure if the issue you're seeing is similar to the proxy issue, but the latest update to vsts-node-api included some support for proxy servers.  (There are more details about what work that needs to be done in the extension in #51.)

Presumably you're attempting to connect to your on-prem TFS server with HTTPS (SSL)?  Do you know if you're using a proxy as well?  Do you have any other http settings listed in the User Settings or as environment variables?

I expect to begin the work to move to the latest version of vsts-node-api soon but I don't have an ETA yet on completion.

**Comment by alphaCoder** [comment]
Hi Jeff,

Thanks for your quick reply. I don't have any other setting other than "http.proxyStrictSSL": false. 
I don't think I am using any proxy.  Thank you very much for adding it to your priority list.

**Comment by jeffyoung** [comment]
Hi @alphaCoder.  If you were connecting to an on-premises TFS server via HTTPS, I just pushed a change in v1.119.0 that should help this scenario (I'm seeing successful connections already).  If you're still interested, I'd be happy for you to try it out (if you haven't already).

**Comment by rcabr** [comment]
Hi @alphaCoder,
I solved this problem by setting the environment variable NODE_TLS_REJECT_UNAUTHORIZED=0 before launching Code.
Good luck!

**Comment by godsake** [comment]
> Hi @alphaCoder,
> I solved this problem by setting the environment variable NODE_TLS_REJECT_UNAUTHORIZED=0 before launching Code.
> Good luck!

Thanks, works like a charm. 
in bin directory, i edited the file code.cmd and added the variable.

**Comment by timcluyts** [comment]
> Hi @alphaCoder,
> I solved this problem by setting the environment variable NODE_TLS_REJECT_UNAUTHORIZED=0 before launching Code.
> Good luck!

This worked for me too! Thanks a bunch!

**Comment by iarckstr14y** [comment]
![image](https://user-images.githubusercontent.com/62303090/79504528-a67c4380-7ff8-11ea-8f70-d8bbfe3c12fc.png)

Hi, I've tried setting the environment variable and it opens just fine, as seen here: 
![image](https://user-images.githubusercontent.com/62303090/79504655-d4618800-7ff8-11ea-984c-2ea3e3e9dda3.png)

But the second I open a folder, it gives me the local issuer certificate. Does anyone have any ideas? @jeffyoung

**Comment by FlorisDevreese** [comment]
I fixed the issue by setting the `NODE_EXTRA_CA_CERTS` environment variable to the path of the certificate used by Azure DevOps

**Comment by iarckstr14y** [comment]
> I fixed the issue by setting the `NODE_EXTRA_CA_CERTS` environment variable to the path of the certificate used by Azure DevOps

Thank you so much! This worked
