### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by vaindil** [microsoft/azure-repos-vscode#542]
I use the Insiders build of VS Code and I'm unable to sign in. I have the icon in the status bar, but clicking or double-clicking has no effect. I tried to run the `team signin` command, and the command window shows it:
![image](https://user-images.githubusercontent.com/771134/60116458-0b9f3980-9746-11e9-8969-3e4ff8a7de25.png)

but nothing happens when I try to run it:
![image](https://user-images.githubusercontent.com/771134/60116479-178afb80-9746-11e9-9a57-40ee9307f71f.png)

**VS Code**
Version: 1.36.0-insider (user setup)
Commit: e80dd4f217db6e230d311a87fdf4276f740f6445
Date: 2019-06-25T05:19:01.461Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by FlorianLeitgeb** [comment]
I am experiencing the same problem at the moment. FYI I used a code to sign in the first time and it worked like a charm. But the next tim I opened VSCode, I was signed out and now I am unable to sign in.

**Comment by kristualdandamudi** [comment]
same thing happened to me as  @FlorianLeitgeb  , any solution?

**Comment by wp4nuv** [comment]
Just came across this error myself. I'll try reinstalling the extension.
