### ISSUE TITLE
Status bar link to team website does nothing (remote-ssh)

### ISSUE THREAD

**Issue by iamjrock** [microsoft/azure-repos-vscode#547]
The Azure Repos extension adds a link in the VS Code status bar with the hover title "Click to view your team project website.".

When I click this, nothing happens.

We are using the new VS Code Remote functionality such that the Extension is installed on the Remote:
![image](https://user-images.githubusercontent.com/38854392/61178203-cc645a00-a61a-11e9-86e7-5c7e8ce1be9f.png)

Perhaps the Extension is not yet Remote-aware and is trying to open a browser on the Remote instead of on the IDE client machine?

**Comment by emiliodangelo** [comment]
The same happens with _Click to view build_ button:

![image](https://user-images.githubusercontent.com/12235230/68251779-205cd980-0024-11ea-984d-c09fd9b82204.png)
