### ISSUE TITLE
Error acessing on premisses TFS2015 Update 3 behind Load Balancer

### ISSUE THREAD

**Issue by viniciussalmeida** [microsoft/azure-repos-vscode#55]
Hi,

Our TFS2015 setup has a Load Balancer between the clientes and the application servers, all the communication is cryptographed, and when I try to connect with the extension I got this error:

2016-10-11T15:15:05.372Z - error: self signed certificate in certificate chain

But all the certificates in the chain are trusted in my machine.

**Comment by jeffyoung** [comment]
Hi viniciussalmeida,

Thank you for reporting the issue.

We have received a couple of reports similar to this issue ("self signed certificate in certificate chain") and will need to investigate further.  However, I don't have an ETA on when we'll be able to do that and then produce a fix.  That said, I'll certainly add it to our backlog.

Thanks again for letting us know (and for trying out the extension)!
