### ISSUE TITLE
Extension doesn't recognize open folder as Git repository

### ISSUE THREAD

**Issue by yergi** [microsoft/azure-repos-vscode#550]
After finally figuring out that I should not url encode the spaces in our Team Name, I finally connected to our on-prem TFS 2018 instance. However, none of the Git-related features work. I get the following error:

> The open folder is not a Git repository. Please check the folder location and try again.

This is absolutely incorrect - it _is_ a Git repo, and all of the other Git-related extensions / capabilities of VS Code are working appropriately.

**Comment by yoyoys** [comment]
I have this problem too, any one help?
