### ISSUE TITLE
Connecting to the wrong project. 

### ISSUE THREAD

**Issue by tlewers** [microsoft/azure-repos-vscode#558]
I have several project in azure devops and every time I open my folder locally for one of the projects it connects to the wrong project in my devops account.  

How do I change which project that vs code connects to with the plugin?  

See below image,  What is circled how do I change that?  
 
![image](https://user-images.githubusercontent.com/34103495/63284635-9a798f80-c279-11e9-8035-f000d55cc782.png)

**Comment by veepee78** [comment]
Same here. Connects to wrong project. My local workspace is for different project. I used automatic token to connect and version in use is 1.149.2.

**Comment by BrandonWandon** [comment]
Same happens for me. It seems to be updating the correct project, but the wrong one is listed at the bottom.
