### ISSUE TITLE
'View History' URL is incorrect

### ISSUE THREAD

**Issue by adam-marshall** [microsoft/azure-repos-vscode#562]
Steps to reproduce:

1. Select a file in VS Code
2. Press F1 and select command 'Team: View History'

Result:
Browser tab opens, at the URL:
![image](https://user-images.githubusercontent.com/2521384/64949687-a5701180-d871-11e9-9586-9ee0a098dbfd.png)

This fails, and you are taken to the top level of Azure DevOps (projects)

Expected URL format is:
![image](https://user-images.githubusercontent.com/2521384/64949665-98ebb900-d871-11e9-9a5c-e6020503b819.png)

May only affect single projects? This means the 'View History' feature is pretty useless. Would definitely be beneficial to have an option in the right-click context menu for files too.

**Comment by nedex** [comment]
Can confirm, in my case the base url is:
> **server**:**port**/tfs/projects/?path

instead of

> **server**:**port**/tfs/projects/**projectName**/_versionControl?path

It's probably related to the migration of TFS to TFS2019.
