### ISSUE TITLE
Unable to check in to TFS 2017

### ISSUE THREAD

**Issue by sujeetkp** [microsoft/azure-repos-vscode#565]
I have installed Azure Repos plugin to integrate VSCode with TFS. But when I am trying to check in it fails. I believe it is because while checking in it is expecting a comment to be passed but Azure Repo plugin doesn't pop up for any comment.

I verified the command that it uses to check in and executed manually. That pops up for a comment.
Please help.

**Comment by jvsca** [comment]
Same issue.
