### ISSUE TITLE
Source Control window (TFVC) is blank but icon shows changes

### ISSUE THREAD

**Issue by AlphaCreative-Mike** [microsoft/azure-repos-vscode#571]
Issue Type: <b>Bug</b>

Edit a file in a server workspace.  The icon increments but the Source Control window is blank.  This started happening after a recent Visual Studio Code or Visual Studio 2019 update.
![image](https://user-images.githubusercontent.com/55245585/66753624-3a126300-ee62-11e9-8edf-515e9f8c7b2c.png)

Extension version: 1.149.2
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jfrahm1987** [comment]
I have found that in the settings there are now errors after the VS Code 1.39.1 update that may be related. When I try to correct them I receive the error at the bottom of the screenshot.
![2019-10-15_08-32-30](https://user-images.githubusercontent.com/14897208/66836274-a9518b00-ef26-11e9-9bcd-86ed290e5418.png)

**Comment by AlphaCreative-Mike** [comment]
Mine was set to '0' so I didn't have this issue. There is obviously something wrong though because this value is not required for TFVC as it states in the description.

**Comment by jfrahm1987** [comment]
Mine was set to 0 before the update. I get the error when I try to put the zero back. I tried just putting it in the json file but it still gives me errors.

**Comment by nmklotas** [comment]
After update Visual Studio Code 1.39.1 this bug happens to me too

**Comment by AlphaCreative-Mike** [comment]
This issue was resolved in 1.39.2.  https://github.com/microsoft/vscode/issues/82203
