### ISSUE TITLE
Octicons not Rendering in bottom task bar

### ISSUE THREAD

**Issue by mcollier** [microsoft/azure-repos-vscode#572]
Issue Type: <b>Bug</b>

Git icons are not showing on the bottom task bar. Instead of the icon, I see placeholders such as "$(icon octicon-getpull-request)" and "$(icon octicon-package)" There are 5 placeholders that all begin with "$(icon octicon-)".
![vscode octicon error](https://user-images.githubusercontent.com/1142273/66802739-51893480-eed2-11e9-8837-41bd6a51f78a.png)

Related to https://github.com/microsoft/vscode/issues/82511

VS Code version: Code - Insiders 1.40.0-insider (ceeb587991f647659d42a82f87acf3d9778b4d0e, 2019-10-14T10:20:22.455Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
armview|ben|0.3.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.31.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.22
docs-preview|doc|0.3.34
docs-yaml|doc|0.2.4
xml|Dot|2.5.0
gitlens|eam|10.1.1
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.14
docker-explorer|for|0.1.6
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.12.0
rest-client|hum|0.22.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
vscode-logicapps|ms-|0.2.18
vscode-asa|ms-|0.1.5
mssql|ms-|1.6.0
python|ms-|2019.10.41019
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.7.0
material-icon-theme|PKi|3.9.1
polacode|pnp|0.3.4
quicktype|qui|12.0.46
vscode-yaml|red|0.5.3
bash-debug|rog|0.3.6
gi|rub|0.2.11
arm-snippets|sam|1.4.19
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.7.18
azure-event-hub-explorer|Sum|0.1.2
todo-list|Tza|1.5.1
vscodeintellicode|Vis|1.1.9
azure-iot-toolkit|vsc|2.11.0
vscode-icons|vsc|9.4.0

(1 theme extensions excluded)

Extension version: 1.149.2
VS Code version: Code - Insiders 1.40.0-insider (3d3202804b4644f58cfac014e39b77dd36a6d226, 2019-10-14T21:15:27.586Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AVDW** [comment]
This has been bugging me for a while now. I've created a pull request that fixes it. Not 100% sure if its the right way to go about it but I have seen some work happening on the vscode repo regarding octicons.

**Comment by mcollier** [comment]
@AVDW Is this your PR for the fix - https://github.com/microsoft/azure-repos-vscode/pull/573?

**Comment by misolori** [comment]
cc @jrbriggs, this will affect all users on Stable once it is released in a few weeks. Recommendation is to not reference `octicon` in your icons but rather just call the icon explicitly ([see our docs](https://code.visualstudio.com/api/references/icons-in-labels)). PR https://github.com/microsoft/azure-repos-vscode/pull/573 seems to fix this.

**Comment by AVDW** [comment]
@mcollier Yes that's my PR. It's essentially doing exactly what @misolori has mentioned.
