### ISSUE TITLE
Source Control Panel Blank - VSCode 1.40.0-insider

### ISSUE THREAD

**Issue by timdang** [microsoft/azure-repos-vscode#586]
Related to https://github.com/microsoft/azure-repos-vscode/issues/570 that was fixed by @joaomoreno with https://github.com/microsoft/vscode/issues/82203

As of Version: 1.40.0-insider commit c58aaab8a1cc22a7139b761166a0d4f37d41e998, the panel is once again blank. So, once this Insider's branch gets promoted to general release, the blank Source Control panel will return.

**Comment by joaomoreno** [comment]
Discussion is still ongoing in https://github.com/microsoft/vscode/issues/82203#issuecomment-545334334

**Comment by joaomoreno** [comment]
Created https://github.com/microsoft/azure-repos-vscode/pull/590

I don't know if this fixes @timdang's issue. I spent 2 hours trying to use this extension. I fail to set it up using TEE in Linux. I failed to set it up on Windows: https://github.com/microsoft/azure-repos-vscode/pull/590

I simply can't use it.

**Comment by timdang** [comment]
Fixed by https://github.com/microsoft/vscode/issues/83440
