### ISSUE TITLE
Can't login to TFS

### ISSUE THREAD

**Issue by nkamenar** [microsoft/azure-repos-vscode#599]
When I try to log in to TFS using my work credentials I just get that authentication is failing but I don't really know why. Below I am including an image of the output I see in the TFVC output window. I know the credentials are correct because I can use them to log into the TFS web portal. This is an on premises TFS server using our windows accounts FYI.

![vscode tfs fail](https://user-images.githubusercontent.com/8999291/68954990-1315bc80-0793-11ea-871c-45fc9c66dbee.png)

**Comment by ianepreston** [comment]
I've got the same issue. Just started yesterday even though I didn't update VS code or the extension, and nothing changed with our on prem TFS server.
![image](https://user-images.githubusercontent.com/17241371/69880970-b6cd9500-1288-11ea-8503-f7dc9b4d34e9.png)
Azure repos 1.161.0
VS code 1.40.2

**Comment by nkamenar** [comment]
Can we get a confirmation that this is a bug and being looked into or are we missing something? This is preventing our team from using vscode because we can't get it to connect to our source control. It does look like the login is successful because I get a list of pending changes to show up when I sign in but I can't actually do anything because it says unauthorized when I try anything.

**Comment by ianepreston** [comment]
> n I sign in but I can't actually do anything because it says unauthorized when I try anything.

Exact same issue here. Changes show up but I can't commit them.

**Comment by trenaryja** [comment]
+1

**Comment by BrandonWandon** [comment]
+1

**Comment by Scholar17** [comment]
same issue here. Cannot solve untill 2020?
