### ISSUE TITLE
TFS Issues - Visual Studio Code

### ISSUE THREAD

**Issue by PawelMaslak** [microsoft/azure-repos-vscode#609]
I have tried to connect TFS to Visual Studio code, followed then all steps needed to set up this and the message I receive is:

"It appears you are using a Server workspace. Currently, TFVC support is limited to Local workspaces."

Of course I googled for this and found loads of topics similar to that so I tried:

>  Configure the "tfvc.location" in VS Code, with VS2017 TF.exe file "C:\Program Files (x86)\Microsoft Visual Studio\2017\TeamExplorer\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe" (recommended to also add to the system path)
> Open VS2017, and in team explorer home -> solutions panel -> click on the workspace -> Manage workspaces... -> Edit -> Advanced -> Change it to server -> Save and wait it finalize the process -> go back there and now change to local. (If it do not work, recreate the whole workspace)
> To make sure that everything is Ok, open a command line and type: tf.exe workspaces /format:detailed /collection:xxxx. If it shows that it is a local workspace, it is all good.
> Now in VS code, uninstall TFVC, reload it, then install it again.

AND

> Open Developer Command Prompt for VS 2017
> Navigate to the workspace root folder
> Enter "tf workspace"
> Login
> 
It does not ask me to login as I can see working folders in this workspace so I assume I am logged in. Unfortunately this is not helping. I also checked for detailed info about Workspace:

> Workspace  : ABC
> Owner      : ABC
> Computer   : ABC
> Comment    :
> Collection : abc\DefaultCollection
> Permissions: Private
> Location   : Local
> File Time  : Current

The message stays the same. I use latest issue of VS Code and VS 2019.

Has anyone found permanent fix to this issue?

**Comment by gevlee** [comment]
I also have the same issue. I've been trying all of "googled" workarounds - nothing helps.

**Comment by PawelMaslak** [comment]
> I also have the same issue. I've been trying all of "googled" workarounds - nothing helps.

The way around this issue is to open your project in Visual Studio and commit from there. The disadvantage of this is very unfortunate as Visual Studio does not detect changes in the code so I have to delete project from source control and then add it once again. Still, I find it better than losing your code so I do that. It's so surprising that VS Code works so fine with GIT whereas with TFS is total shambles.

**Comment by gevlee** [comment]
I solved it in my case. The problem was in login credentials... when i typed login with domain (domain\username) it has started working. I had to debug the exetension to discover it :)
