### ISSUE TITLE
Team:Signin command failed

### ISSUE THREAD

**Issue by Reinhardt2019** [microsoft/azure-repos-vscode#610]
After I configure the TFVC successfully as "TFVC Support" Website said, I run the "Team:Signin" in the command platette, but the command platette disappeared and showed the error in the right-bottom side of VSCode.
The error showed differently when I run the "Team:Signin" command, which are

1. command 'team.Signin' not found
or
2.(team) No Azure DevOps Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder that contains a repository.

**Comment by gethari** [comment]
@Reinhardt2019 this worked for me [Thread](https://github.com/Microsoft/azure-repos-vscode/issues/371#issuecomment-527514534)
