### ISSUE TITLE
Can not sign in

### ISSUE THREAD

**Issue by BrandonWandon** [microsoft/azure-repos-vscode#616]
I have this set up and working on an older version on my work PC. Now that I am working from home, I set it up on my PC at home and it will not work. It's set up the same way and I can access the Azure DevOps site. I can manually run TF commands perfectly fine and it also works from Visual Studio. But when I try to do anything in Visual Studio Code, it says that I need to run team signin. When I run that, I get no errors, but it never signs in. I can run the commands manually that show in the output in a command line with no issues or errors.

**Comment by stanspotts** [comment]
I have the same issue. If I run Team: SignIn I am prompted for my NTLM domain\account, which is actually pre-filled and correct. Hit <enter> and then prompt for password, which I enter correctly,

Then nothing. Ho indication whether it worked or not. Except on the bottom I see Team(X), And when I hover over it, I see "Unauthorized. Check your authentication credentials and try again."

The repo I'm working with was cloned from the command line with git. I can do a pull, push, etc. from the command line to the remote. But I can't work with the remote from VS Code.

**Comment by JustinGrote** [comment]
@jrbriggs are you still primary on this project? Everyone has this issue vs. using manual signin
