### ISSUE TITLE
Support Azure Board exclusive of Azure Repo

### ISSUE THREAD

**Issue by mimam419** [microsoft/azure-repos-vscode#618]
Currently, you need to use Azure Repo if you want to use Azure Board.
Since the Azure teams itself support other repositories, there are high possibility of using the Azure board without the Azure Repo.
As it stands now, you can not even initialize this extension if it cannot find an Azure repository in your current directory.
I strongly feel that this should be decoupled as it is currently done with [JIRA and BitBucket Official](https://bitbucket.org/atlassianlabs/atlascode)

**Comment by bschnurr** [comment]
I am looking for this as well. My code and work items live in two different repos in different organizations in azure devops.
