### ISSUE TITLE
Unable to store credentials for host

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-repos-vscode#62]
After installing a new SSD in my Macbook Pro (cloning the old one), VS Code wasn't able to connect to VSTS anymore. Because of the order that I tried things in, I ended up invalidating the old PAT and creating a new one, so I needed to `team login` again. I got an error "unable to store credentials for this host". It had partially succeeded though: Keychain Access showed a "team:<myaccount>.visualstudio.com" entry with the right timestamp but no password. I pasted the PAT in Keychain Access, then went back to Code and hit the sync button. This time, an OS-level message popped up asking if I wanted to grant VS Code access to the keychain item. I chose "always allow" and now things seem to be working fine.

There may not be much you can do in this situation. Filing a bug with detailed-ish repro steps since I saw this comment in the code: `// TODO: Should the message direct the user to open an issue?  send feedback?`

**Comment by jeffyoung** [comment]
Thanks for reporting Matt.  That'll be good information to have when I have a look at some other keychain-related issues.

**Comment by fedorinoGore** [comment]
Have a similar error while installing Team Services for the first time. Could you please help with workaround? How to correctly add PAT to the Key Chain on OS X?

**Comment by vikasgorur** [comment]
I'm trying to setup the extension for the first time as well and have multiple issues:

1) Pasting / Cmd-V does not seem to work in the command palette when it asks for the PAT.

2) I opened up Keychain and manually set the "password" field to the PAT but it still asks me for the token or just says "Unable to store credentials for host".

These are the contents of my keychain entry:

```
Name: team: myteamname.visualstudio.com
Kind: application password
Account: OAuth
Where: team: myteamname.visualstudio.com
```

Please let me know if I can supply any more information. Thanks in advance from a very happy user of VS Code!

**Comment by chadbr** [comment]
getting this issue now - worked for months - but it won't take a new token

**Comment by chadbr** [comment]
I wish I would have read the details above 2 weeks ago :)

deleting the ```team:.visualstudio.com``` entry from keychain made it work

**Comment by ToAnuranjans** [comment]
Hi,

I am facing the same issue but not sure how to find keychain on windows 10 to delete team:.visualstudio.com entry to fix this annying problem.

Thanks in advance..

**Comment by ToAnuranjans** [comment]
@chadbr can you please help me locate team:.visualstudio.com as I am too facing the similar issue on my windows machine.

**Comment by chadbr** [comment]
sorry - I'm not sure where it's stored on Windows...

**Comment by chadbr** [comment]
Ok, I was curious -- found it here... https://github.com/Microsoft/vsts-vscode/blob/master/src/credentialstore/win32/win-credstore-api.ts#L143

look in credential manager (duh!)

![image](https://user-images.githubusercontent.com/3179452/28622249-7ccc09ba-71d9-11e7-8b6f-37c72ab5483f.png)

**Comment by ScottGross** [comment]
this is happening with MacOS as well now. any ideas?

**Comment by chadbr** [comment]
on mac:

-press command + space
-type keychain
-select "Keychain Access"

![image](https://user-images.githubusercontent.com/3179452/31682537-f9d454c4-b33f-11e7-8396-39d743431222.png)


-on the left, click on "login" on the top, "password" on the bottom
-scroll down to the t's in the list until you see team:...visualstudio.com 
-right click and select "delete"

**Comment by chadbr** [comment]
also fwiw, if you use the "new experience" when logging in - this doesn't happen to me anymore.

**Comment by ScottGross** [comment]
that worked thank you!
