### ISSUE TITLE
vscode checkin comment chinese disorderly code

### ISSUE THREAD

**Issue by diaodiaop** [microsoft/azure-repos-vscode#620]
vscode ver: 1.45.1

tf ver:vs2019 built-in

![image](https://user-images.githubusercontent.com/6956543/82984314-80e54f80-a024-11ea-8b10-9b56df115425.png)

![image](https://user-images.githubusercontent.com/6956543/82986907-4205c880-a029-11ea-89db-a52c4c5559da.png)

but  if use cmd

> tf checkin d:1.txt -comment:备注

no problem

change vs code language  Same problem

see more  [https://bbs.csdn.net/topics/396659728](https://bbs.csdn.net/topics/396659728)

**Comment by xcGithub** [comment]
なんとなくきつい  何を書いていますか？意味が分かりません。

**Comment by weilun-123** [comment]
卧槽，我跟你一样也是中文签入乱码，
https://github.com/microsoft/azure-repos-vscode/issues/627，你是怎么解决的？
