### ISSUE TITLE
Is this extension Abandoned?

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/azure-repos-vscode#621]
@jrbriggs can we get a status or roadmap? No commits in 6 months makes me think this project has been abandoned...

**Comment by ausfestivus** [comment]
Paging @jrbriggs. Mr Briggs to the courtesy phone please.

**Comment by JustinGrote** [comment]
Looks like @jrbriggs dropped off the face of github in April...
![image](https://user-images.githubusercontent.com/15258962/91233583-62a3f400-e6e6-11ea-9571-25d6298564b0.png)

**Comment by ausfestivus** [comment]
Had a look through https://github.com/microsoft/azure-repos-vscode/graphs/contributors. Lets page @jeffyoung and @jpricket since they are the two most active members of the repo before it went dark. I note though that both of them have  been fairly quiet in GH as well but it's a start.

**Comment by jpricket** [comment]
@ausfestivus @JustinGrote - Unfortunately with the transition of Azure Dev Ops into GitHub, teams have moved around a ton. I will try to find out who owns this now and what the status is. I do know that there was a lot of demand for this extension when we created it and so hopefully we can continue to support it.

**Comment by JustinGrote** [comment]
@jpricket thanks, FYI the extension now has over a million downloads and a two star rating, mostly because some basic login issues are broken that can be easily fixed.
![image](https://user-images.githubusercontent.com/15258962/91317135-8743ae80-e76e-11ea-8643-d25080ed9d9a.png)

**Comment by JustinGrote** [comment]
@jpricket it may also be worth investigating if the work or features can be merged into a separate backend for the Github Pull Requests and Issues extension, which is a far superior and fully featured extension. Having that functionality also able to use the Azure Devops API would be ideally the way to go, after the basic login issue is fixed in this extension making it useful.

**Comment by kilasuit** [comment]
So considering @vtbassmatt pushed and merged #640 without updating anywhere else in the repo - I think its unfortunate & this project is being wrongly abandoned

**Comment by JustinGrote** [comment]
@kilasuit The description assumes that people only used this for VSTS which is completely false, it was an excellent way to quickly access issues, bugs, and other items related. I am going to close this issue since it has been basically answered by #640 but agree this is disappointing without providing a forward path.
