### ISSUE TITLE
Wont allow to sign in

### ISSUE THREAD

**Issue by benvb1234** [microsoft/azure-repos-vscode#622]
Issue Type: <b>Bug</b>

After downlaoding this extension, I looked up Teams SignIn but it gives an error right away. I have tried multiple times and even have re-started

Extension version: 1.161.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (53.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by GarrettDavis** [comment]
Same here. I've tried both the "current experience" of providing a PAT and the "new experience". I'm not sure when it stopped working, but this has worked with previous versions of the extension and VSCode. I'm sorry I can't provide the version(s) where this stopped working for me.

**Comment by abhinavaGopagani** [comment]
I am getting this error
Command 'Team: Signin' resulted in an error (command 'team.Signin' not found)

**Comment by chrisbues** [comment]
Same here.
