### ISSUE TITLE
Drop TFVC support but retain the rest of the functionality

### ISSUE THREAD

**Issue by cpdohert** [microsoft/azure-repos-vscode#641]
"This extension [...] allows you to monitor your builds and manage your pull requests and work items"

My team makes heavy use of these features even though we don't use TFVC.  I can't fault you for sunsetting TFVC support, but having these additional features is useful.  Is it possible to drop TFVC support but retain the extension for these features?

**Comment by CharlesNadolskiNtrs** [comment]
Another option I could get behind would be to let the community take over this extension, and remove TFVC support.  Our team uses every other feature in this extension *except* for TFVC support.

**Comment by OranguTech** [comment]
Came here to post nearly the exact same issue. We only very touch TFVC (though we have some), but I use this for creating PRs all the time at least.

**Comment by mdschweda** [comment]
Agreed. Make this an Azure Boards extensions + PR support. The [GitHub extension](https://code.visualstudio.com/docs/editor/github) is vastly superior in this aspect.

**Comment by kilasuit** [comment]
As a big user of Azure DevOps & particularlly git repos (almost no TFVC repos in day to day use) and the functionality within this extension is still incredibly useful to many

**Comment by salgiza** [comment]
I've been using this extension since the beginning and I didn't even remember that it supported TFS...
So the message that Microsoft is sending is that if we want to integrate work items with VS Code we should migrate to Github?

**Comment by erikread** [comment]
Our product uses TFS exclusively. No git whatsoever.
This is very disheartening as it will make day to day use of VS Code much more time consuming (open Visual Studio just to do checkouts).

**Comment by collinstevens** [comment]
@salgiza my team also has no use of TFS as we only use this to work with Azure DevOps Git Repos... very frustrating since this is a daily driver of our workflow. The ability to create pull requests from the tool alone is reason enough to use it. They should just drop TFVC support from the tool and tailor this extension specifically to Azure DevOps Repos, which is the name of the extension itself...

**Comment by phantasm33** [comment]
This is bad news. Contrary to popular belief there are many us who still use TFVC as our main source control. Most of us have source code that has been migrated from VSS  to TFS to Azure DevOps. Our dev teams are well versed on TFVC and don't use Git or GitHub. I wish Microsoft would stop pushing everyone down their preferred path and recognize that some organizations are not upgrading at the speed of light. Even as recently as last week's Ignite, all of the talk was of GitHub. It's like they forgot all about DevOps Repos. Very frustrating.

**Comment by cpdohert** [comment]
@phantasm33 
>all of the talk was of GitHub. It's like they forgot all about DevOps Repos.

There's a persistent rumour going around that since buying GitHub, Microsoft is sunsetting all of Azure DevOps in favour of GitHub Enterprise.  Allegedly the entire AzDO team is being slowly migated over and tasked with bringing feature parity to GitHub Enterprise.

I don't want to believe it, but over the last three years I've watched MS repeatedly throw its long-time customer base under the bus in favour of courting the open-source/Linux market and it's entirely plausible.  And every time I see an announcement like this it reinforces that opinion.

**Comment by Tiberriver256** [comment]
I didn't even know this extension could do anything with TFVC. I use it for work item linking / PR / build monitoring / etc.

I agree, between this and with newer Azure features getting Github support first... it looks like if they're not dropping Azure DevOps it is sure losing some funding or something.
