### ISSUE TITLE
Where to obtain TF.EXE client?

### ISSUE THREAD

**Issue by dnesting-usa** [microsoft/azure-repos-vscode#645]
I appreciate the reasons behind deprecating this plugin.

The [deprecation notice](https://github.com/microsoft/azure-repos-vscode/blob/master/DEPRECATED.md) states that if we want to continue using VS Code with TFVC, we'll need to use a command-line client, like `tf.exe`.  The page links to a [`tf.exe` command reference page](https://docs.microsoft.com/azure/devops/repos/tfvc/use-team-foundation-version-control-commands).  This page has some basic instructions on where to find `tf.exe` on your system, but these instructions assume it's installed with your Visual Studio installation.  It's unlikely that VS Code users will have a Visual Studio installation.

Can you provide a link for VS Code users to install the TFVC command-line client?

(Or if the TFVC client does, in fact, require that we install Visual Studio, that implies the deprecation notice needs to be rewritten to state the reality that this deprecation means VS Code users have no options for accessing TFVC and they will need to license/install Visual Studio instead.)

**Comment by CharlesNadolskiNtrs** [comment]
Here's an indirect and officially sanctioned way to get tf.exe without having to purchase the full version of Visual Studio:
Go to https://visualstudio.microsoft.com/downloads/
and search for:
Visual Studio Team Explorer 2019 

And yes, these instructions should belong in the deprecation notice.

**Comment by dnesting-usa** [comment]
Thanks, Charles.  I found the download for Visual Studio Team Explorer 2019, but upon downloading, it requires me to agree to license terms at https://visualstudio.microsoft.com/license-terms/mlt031619/. These terms appear to require that I have a full license for Visual Studio, or else the installation is for a 30-day trial.  So this does not appear to be a valid path forward.

> MICROSOFT VISUAL STUDIO ENTERPRISE 2019, VISUAL STUDIO PROFESSIONAL 2019, VISUAL STUDIO TEST PROFESSIONAL 2019 AND TRIAL EDITION
>
> ...
>
> TRIAL EDITION USE RIGHTS. If you have not acquired a valid full-use license, the software is a trial edition, and this Section applies to your use of the trial edition.
>
>A. GENERAL. You may use any number of copies of the trial edition on your devices. You may only use the trial edition for internal evaluation purposes, and only during the trial period. You may not distribute or deploy any applications you make with the trial edition to a production environment. You may run load tests of up to 250 virtual users during the trial period.
>
> ...

**Comment by CharlesNadolskiNtrs** [comment]
No license is required, unless the installer got totally broken.  This is from the download page:
Visual Studio Team Explorer 2019
A **free** solution for non-developers to interact with Azure DevOps Server and Azure DevOps. Please see the Release Notes for more information.

**Comment by dnesting-usa** [comment]
Thanks for the ideas.  While I appreciate that it says "free" in that sentence, I am not a "non-developer", and the license agreement takes precedence over the description.

![image](https://user-images.githubusercontent.com/25333309/96520932-23090c80-123e-11eb-921e-f025c8e9d97f.png)

![image](https://user-images.githubusercontent.com/25333309/96521011-48961600-123e-11eb-9e45-9d8085448819.png)

https://visualstudio.microsoft.com/license-terms/mlt031619/

![image](https://user-images.githubusercontent.com/25333309/96521099-79764b00-123e-11eb-99a5-d7727d5150a9.png)

Sadly, I don't have the luxury in my professional capacity of ignoring things like this.  :(

Thank you again.

**Comment by CharlesNadolskiNtrs** [comment]
Maybe you can call a rep from Microsoft about the licensing? Sounds like the wires may have gotten crossed in the licensing links.  I totally get staying on top of licenses at a large organization.  For what it's worth, in my organization almost everybody on the tech side had Team Explorer installed by default regardless if they were technical or not or which stack they were working on, because TFS was the only thing supported before Git took off.

**It would be nice if somebody who represents Microsoft can clear up this conundrum.**
